package com.crypto.laplace.audit;

public enum VolumeScanTransition { ENTERED_POOL, REMAINED_ACTIVE, MOVED_TO_WATCHLIST, REMAINED_WATCHLIST, ELIMINATED_FROM_POOL, REMAINED_ELIMINATED, REACTIVATED, NOT_EVALUATED }
