package com.crypto.laplace.model;

public enum PositionManagementOutcome {
    ALREADY_PROCESSED, NO_ACTION, PARTIAL_EXIT, CLOSED_STOP_LOSS, CLOSED_BREAK_EVEN,
    CLOSED_5C_LONG_FAST_REGIME, CLOSED_SHORT_EMA20_ACCEPTANCE
}
