package com.crypto.laplace.model;
public enum RejectionReason { STARTUP_WARMUP, INSUFFICIENT_CANDLES, OPEN_CANDLE_DETECTED, ATR_UNAVAILABLE, ATR_ZERO, SLOPE_IN_DEAD_ZONE, SECOND_CONFIRMATION_MISSING, CLOSE_NOT_ABOVE_REGRESSION, CLOSE_NOT_BELOW_REGRESSION, DUPLICATE_CANDLE, SYMBOL_NOT_IN_STARTUP_UNIVERSE, DATA_GAP, REGRESSION_UNAVAILABLE }
