package com.crypto.laplace.session;

import com.crypto.common.enums.PositionSide;
import com.crypto.laplace.config.LaplaceStrategyProperties;
import com.crypto.laplace.execution.LaplacePaperExecutionService;
import com.crypto.laplace.execution.LaplacePaperTradeCoordinator;
import com.crypto.laplace.model.LaplacePositionStatus;
import com.crypto.laplace.persistence.LaplacePaperPositionRepository;
import com.crypto.laplace.scheduler.LaplaceThirtyMinuteScheduler;
import com.crypto.laplace.service.LaplaceBreadthService;
import com.crypto.laplace.service.LaplaceStartupHistoryService;
import com.crypto.laplace.service.StartupMarketUniverseService;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.Duration;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.locks.ReentrantReadWriteLock;
import java.util.function.Supplier;
import java.util.function.Consumer;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.core.annotation.Order;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

/** Session-only risk controls around the unchanged KURAL5 signal and position lifecycle. */
@Slf4j @Service @Order(300)
@ConditionalOnProperty(prefix="trading.laplace",name="enabled",havingValue="true")
public class LaplaceSessionManager implements ApplicationRunner {
 public static final String PROFIT_LOCK_REASON="SESSION_PROFIT_LOCK_5PCT_REALIZED_4_6PCT_PROJECTED",CUTOFF_REASON="BLOCK_SESSION_ENTRY_CUTOFF_10H",HARD_CLOSE_REASON="EXIT_SESSION_HARD_CLOSE_12H",LONG_CAP_REASON="BLOCK_LONG_30M_SLOT_CAP_5",VOLUME_REASON="BLOCK_CURRENT_24H_VOLUME_BELOW_20M",STALE_REASON="BLOCK_STALE_PREVIOUS_SESSION_SIGNAL";
 public enum Lifecycle {ACTIVE,LOCKED,RESETTING,RISK_OFF}
 private final LaplaceStrategyProperties properties;private final LaplacePaperExecutionService execution;private final LaplacePaperPositionRepository positions;private final StartupMarketUniverseService universe;private final LaplaceStartupHistoryService history;private final LaplaceBreadthService breadth;private final ObjectProvider<LaplacePaperTradeCoordinator> coordinator;private final ObjectProvider<LaplaceThirtyMinuteScheduler> scheduler;private final ReentrantReadWriteLock lifecycleLock=new ReentrantReadWriteLock(true);private final Supplier<Instant> clock;
 private final String tradingRunId=UUID.randomUUID().toString();private volatile Snapshot state;
 public LaplaceSessionManager(LaplaceStrategyProperties properties,LaplacePaperExecutionService execution,LaplacePaperPositionRepository positions,StartupMarketUniverseService universe,LaplaceStartupHistoryService history,LaplaceBreadthService breadth,ObjectProvider<LaplacePaperTradeCoordinator> coordinator,ObjectProvider<LaplaceThirtyMinuteScheduler> scheduler){this(properties,execution,positions,universe,history,breadth,coordinator,scheduler,Instant::now);}
 LaplaceSessionManager(LaplaceStrategyProperties properties,LaplacePaperExecutionService execution,LaplacePaperPositionRepository positions,StartupMarketUniverseService universe,LaplaceStartupHistoryService history,LaplaceBreadthService breadth,ObjectProvider<LaplacePaperTradeCoordinator> coordinator,ObjectProvider<LaplaceThirtyMinuteScheduler> scheduler,Supplier<Instant> clock){this.properties=properties;this.execution=execution;this.positions=positions;this.universe=universe;this.history=history;this.breadth=breadth;this.coordinator=coordinator;this.scheduler=scheduler;this.clock=clock;}
 @Override public void run(ApplicationArguments ignored){lifecycleLock.writeLock().lock();try{startFresh(null);}finally{lifecycleLock.writeLock().unlock();}}
 @Scheduled(fixedDelayString="${trading.laplace.session-check-delay-ms:60000}") public void tick(){lifecycleLock.writeLock().lock();try{if(state==null)return;Instant now=clock.get();state=state.withMetrics(metrics());if(state.lifecycle()==Lifecycle.RISK_OFF){retryRiskOff();return;}if(!now.isBefore(state.endsAt())){hardReset();return;}if(state.lifecycle()==Lifecycle.LOCKED)return;if(profitLock(state.metrics())){closeForProfitLock();return;}if(!now.isBefore(state.entryCutoffAt())&&state.entryEnabled()){state=state.withEntry(false,CUTOFF_REASON);logContext(CUTOFF_REASON,null,null,null);}}finally{lifecycleLock.writeLock().unlock();}}
 public ScanContext beginScan(){tick();lifecycleLock.readLock().lock();try{Snapshot s=state;if(s==null||s.lifecycle()!=Lifecycle.ACTIVE)return new ScanContext(null,Map.of());return new ScanContext(s.id(),universe.currentVolumeSnapshot());}finally{lifecycleLock.readLock().unlock();}}
 public void processScan(Consumer<ScanContext> scan){tick();lifecycleLock.readLock().lock();try{Snapshot s=state;if(s==null||s.lifecycle()!=Lifecycle.ACTIVE)return;scan.accept(new ScanContext(s.id(),universe.currentVolumeSnapshot()));}finally{lifecycleLock.readLock().unlock();}}
 public boolean allowEntry(String expectedSessionId,String symbol,PositionSide side,Instant slot,Map<String,BigDecimal> volumes,boolean selectedLong,int candidateCount){lifecycleLock.readLock().lock();try{Snapshot s=state;if(s==null||expectedSessionId==null||!expectedSessionId.equals(s.id())){logContext(STALE_REASON,symbol,slot,null);return false;}if(s.lifecycle()!=Lifecycle.ACTIVE||!s.entryEnabled()){logContext(CUTOFF_REASON,symbol,slot,null);return false;}BigDecimal volume=volumes.get(symbol);if(volume==null||volume.compareTo(universe.minimumVolumeThreshold())<0){logContext(VOLUME_REASON,symbol,slot,volume);return false;}if(side==PositionSide.LONG&&!selectedLong){logContext(LONG_CAP_REASON,symbol,slot,volume);return false;}logContext("ENTRY_SESSION_GUARDS_PASSED",symbol,slot,volume);return true;}finally{lifecycleLock.readLock().unlock();}}
 public boolean executeEntry(String expectedSessionId,String symbol,PositionSide side,Instant slot,Map<String,BigDecimal> volumes,boolean selectedLong,int candidateCount,Runnable open){lifecycleLock.readLock().lock();try{if(!allowEntry(expectedSessionId,symbol,side,slot,volumes,selectedLong,candidateCount))return false;open.run();return true;}finally{lifecycleLock.readLock().unlock();}}
 public boolean processSignal(String expectedSessionId,Runnable processing){lifecycleLock.readLock().lock();try{if(!isCurrentSession(expectedSessionId)){log.info("SESSION_SIGNAL_BLOCKED reason={} expectedSessionId={} currentSessionId={}",STALE_REASON,expectedSessionId,currentSessionId());return false;}processing.run();return true;}finally{lifecycleLock.readLock().unlock();}}
 public boolean isCurrentSession(String expectedSessionId){Snapshot s=state;return expectedSessionId!=null&&s!=null&&s.lifecycle()==Lifecycle.ACTIVE&&expectedSessionId.equals(s.id());}
 private boolean profitLock(Metrics m){return m.realizedReturnPct().compareTo(properties.getLaplace().getSessionProfitLockRealizedPct())>=0&&m.projectedReturnPct().compareTo(properties.getLaplace().getSessionProfitLockProjectedPct())>=0;}
 private void closeForProfitLock(){state=state.transition(Lifecycle.RESETTING,false,true,PROFIT_LOCK_REASON);try{execution.closeAllOpen(PROFIT_LOCK_REASON);if(!flat())throw new IllegalStateException("ledger not flat");state=state.transition(Lifecycle.LOCKED,false,true,PROFIT_LOCK_REASON).withMetrics(metrics());logContext(PROFIT_LOCK_REASON,null,null,null);}catch(RuntimeException e){riskOff(PROFIT_LOCK_REASON,e);}}
 private void hardReset(){state=state.transition(Lifecycle.RESETTING,false,state.profitLockTriggered(),HARD_CLOSE_REASON);try{execution.closeAllOpen(HARD_CLOSE_REASON);if(!flat())throw new IllegalStateException("ledger not flat");BigDecimal previous=metrics().realizedReturnPct();clearAndReload();startFresh(previous);logContext("SESSION_HARD_RESET_COMPLETED",null,null,null);}catch(RuntimeException e){riskOff(HARD_CLOSE_REASON,e);}}
 private void clearAndReload(){coordinator.ifAvailable(LaplacePaperTradeCoordinator::clearSessionRuntime);scheduler.ifAvailable(LaplaceThirtyMinuteScheduler::clearSessionRuntime);breadth.clearSessionRuntime();history.clearSessionRuntime();universe.reload();if(!universe.isReady())throw new IllegalStateException("fresh universe unavailable");history.reloadFresh();if(history.readySymbols().isEmpty())throw new IllegalStateException("fresh history unavailable");}
 private void retryRiskOff(){try{execution.closeAllOpen(state.closeReason());if(!flat())return;if(HARD_CLOSE_REASON.equals(state.closeReason())){BigDecimal previous=metrics().realizedReturnPct();clearAndReload();startFresh(previous);}else if(PROFIT_LOCK_REASON.equals(state.closeReason()))state=state.transition(Lifecycle.LOCKED,false,true,PROFIT_LOCK_REASON).withMetrics(metrics());}catch(RuntimeException e){log.error("SESSION_RISK_OFF_RETRY_FAILED sessionId={} closeReason={} error={}",state.id(),state.closeReason(),e.getMessage(),e);}}
 private void riskOff(String reason,RuntimeException e){state=state.transition(Lifecycle.RISK_OFF,false,state.profitLockTriggered(),reason);log.error("SESSION_OPERATION_FAILED sessionId={} lifecycle=RISK_OFF entryEnabled=false closeReason={} error={}",state.id(),reason,e.getMessage(),e);}
 private void startFresh(BigDecimal previous){Instant readyAt=clock.get();BigDecimal capital=execution.accountEquity(),baseCapital=properties.getLaplace().getInitialCapitalUsdt(),baseMargin=properties.getLaplace().getMarginPerPositionUsdt(),margin=baseMargin.multiply(capital).divide(baseCapital,12,RoundingMode.HALF_UP);var c=properties.getLaplace();state=new Snapshot(UUID.randomUUID().toString(),readyAt,readyAt.plus(Duration.ofHours(c.getSessionHours())),readyAt.plus(Duration.ofHours(c.getEntryCutoffHours())),true,Lifecycle.ACTIVE,capital,margin,previous==null?BigDecimal.ZERO:previous,false,"SESSION_STARTED",Metrics.zero());logContext("SESSION_STARTED",null,null,null);}
 private boolean flat(){return positions.findByStrategyAndTradingRunIdAndStatus(LaplacePaperExecutionService.STRATEGY,tradingRunId,LaplacePositionStatus.OPEN).isEmpty();}
 private Metrics metrics(){Snapshot s=state;if(s==null)return Metrics.zero();BigDecimal realized=positions.findByStrategyAndTradingRunIdAndSessionIdAndStatus(LaplacePaperExecutionService.STRATEGY,tradingRunId,s.id(),LaplacePositionStatus.CLOSED).stream().map(p->p.getNetPnl()==null?BigDecimal.ZERO:p.getNetPnl()).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal open=execution.projectedOpenNetPnl(),projected=realized.add(open);return new Metrics(realized,pct(realized,s.capital()),open,projected,pct(projected,s.capital()));}
 private BigDecimal pct(BigDecimal value,BigDecimal capital){return value.multiply(BigDecimal.valueOf(100)).divide(capital,8,RoundingMode.HALF_UP);}
 private void logContext(String reason,String symbol,Instant slot,BigDecimal volume){Snapshot s=state;if(s==null)return;Metrics m=s.metrics();log.info("SESSION_DECISION reason={} symbol={} sessionId={} sessionStartedAt={} sessionAgeMinutes={} lifecycle={} entryEnabled={} sessionStartCapital={} sessionMargin={} realizedSessionNetPnl={} realizedSessionReturnPct={} projectedOpenPositionsNetPnl={} projectedSessionNetPnl={} projectedSessionReturnPct={} profitLockTriggered={} sessionCloseReason={} current24hQuoteVolume={} signal30mSlot={} previousSessionReturnPct={}",reason,symbol,s.id(),s.startedAt(),Duration.between(s.startedAt(),clock.get()).toMinutes(),s.lifecycle(),s.entryEnabled(),s.capital(),s.margin(),m.realized(),m.realizedReturnPct(),m.open(),m.projected(),m.projectedReturnPct(),s.profitLockTriggered(),s.closeReason(),volume,slot,s.previousReturnPct());}
 public String tradingRunId(){return tradingRunId;}public BigDecimal currentSessionMargin(){Snapshot s=state;return s==null?properties.getLaplace().getMarginPerPositionUsdt():s.margin();}public String currentSessionId(){Snapshot s=state;return s==null?null:s.id();}public Instant sessionStartedAt(){Snapshot s=state;return s==null?null:s.startedAt();}public Snapshot snapshot(){return state;}
 public record ScanContext(String sessionId,Map<String,BigDecimal> current24hVolumes){}
 public record Metrics(BigDecimal realized,BigDecimal realizedReturnPct,BigDecimal open,BigDecimal projected,BigDecimal projectedReturnPct){static Metrics zero(){return new Metrics(BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO);}}
 public record Snapshot(String id,Instant startedAt,Instant endsAt,Instant entryCutoffAt,boolean entryEnabled,Lifecycle lifecycle,BigDecimal capital,BigDecimal margin,BigDecimal previousReturnPct,boolean profitLockTriggered,String closeReason,Metrics metrics){Snapshot withMetrics(Metrics m){return new Snapshot(id,startedAt,endsAt,entryCutoffAt,entryEnabled,lifecycle,capital,margin,previousReturnPct,profitLockTriggered,closeReason,m);}Snapshot withEntry(boolean enabled,String reason){return new Snapshot(id,startedAt,endsAt,entryCutoffAt,enabled,lifecycle,capital,margin,previousReturnPct,profitLockTriggered,reason,metrics);}Snapshot transition(Lifecycle next,boolean enabled,boolean profitLock,String reason){return new Snapshot(id,startedAt,endsAt,entryCutoffAt,enabled,next,capital,margin,previousReturnPct,profitLock,reason,metrics);}}
}
