spring:
  datasource:
    url: ${SUPABASE_DB_URL:jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?prepareThreshold=0&sslmode=require}
    username: ${SUPABASE_DB_USERNAME:postgres.wdsxcflkxixvwaqnltkk}
    password: ${SUPABASE_DB_PASSWORD:DhlDi1wQn4XqC749}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
