package com.crypto.laplace.execution;
import static org.mockito.Mockito.*;import static org.assertj.core.api.Assertions.assertThat;import com.crypto.common.enums.PositionSide;import com.crypto.laplace.config.LaplaceStrategyProperties;import com.crypto.laplace.model.*;import com.crypto.laplace.persistence.*;import java.time.Instant;import java.util.*;import org.junit.jupiter.api.BeforeEach;import org.junit.jupiter.api.Test;
class LaplacePaperTradeCoordinatorTest {
 LaplacePaperPositionRepository repo=mock(LaplacePaperPositionRepository.class);LaplacePaperExecutionService execution=mock(LaplacePaperExecutionService.class);LaplaceTradeJsonlWriter writer=mock(LaplaceTradeJsonlWriter.class);LaplaceStrategyProperties config=new LaplaceStrategyProperties();LaplacePaperTradeCoordinator coordinator;
 @BeforeEach void setup(){config.getLaplace().setPaperExecutionEnabled(true);coordinator=new LaplacePaperTradeCoordinator(config,repo,execution,writer);}
 @Test void mapsRawSignalsContrarian(){assertThat(coordinator.mapRawSignalToExecutionSide(LaplaceSignal.LONG)).isEqualTo(PositionSide.SHORT);assertThat(coordinator.mapRawSignalToExecutionSide(LaplaceSignal.SHORT)).isEqualTo(PositionSide.LONG);assertThat(coordinator.mapRawSignalToExecutionSide(LaplaceSignal.NONE)).isNull();}
 @Test void startupBaselineSameSignalDoesNotOpen(){coordinator.initializeBaseline("BTCUSDT",LaplaceSignal.LONG);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.NONE,true),true);verifyNoInteractions(execution);}
 @Test void flatLongOpensExactlyOnce(){when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of());when(execution.open(any(),eq(PositionSide.SHORT),isNull(),eq("FLAT"))).thenReturn(position(PositionSide.SHORT));coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.NONE,true),true);verify(execution).open(any(),eq(PositionSide.SHORT),isNull(),eq("FLAT"));}
 @Test void ineligibleSignalDoesNotOpen(){coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.NONE,false),true);verifyNoInteractions(execution);}
 @Test void paperDisabledDoesNotOpenOrWritePerSignalFailures(){config.getLaplace().setPaperExecutionEnabled(false);coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.NONE,true),true);coordinator.onSignal(signal(LaplaceSignal.SHORT,LaplaceSignal.NONE,true),true);verifyNoInteractions(execution,writer);}
 @Test void sameSideSignalDoesNotPyramid(){when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of(position(PositionSide.LONG)));coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.SHORT,LaplaceSignal.SHORT,true),true);verifyNoInteractions(execution);}
 @Test void strongOppositeReversesButNormalEntryDoesNot(){var p=position(PositionSide.LONG);when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of(p));coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.SHORT,LaplaceSignal.NONE,true),true);verifyNoInteractions(execution);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.LONG,true),true);verify(execution).reverse(any(),eq(p),eq(PositionSide.SHORT),eq(true));}
 @Test void outsideUniverseClosesWithoutOpeningTarget(){var p=position(PositionSide.LONG);when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of(p));coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.LONG,true),false);verify(execution).reverse(any(),eq(p),eq(PositionSide.SHORT),eq(false));}
 private LaplacePaperPositionEntity position(PositionSide side){return LaplacePaperPositionEntity.builder().id("id").symbol("BTCUSDT").side(side).strategy(LaplacePaperExecutionService.STRATEGY).status(LaplacePositionStatus.OPEN).build();}
 private LaplaceSignalResult signal(LaplaceSignal entry,LaplaceSignal reversal,boolean eligible){Instant now=Instant.now();return new LaplaceSignalResult(LaplacePaperExecutionService.STRATEGY,"1.0","BTCUSDT","30m","LAPLACE",14,"CLOSE",false,now.minusSeconds(1800),now,100,99,98,97,1,1,10,10,.1,.1,.03,.04,2,entry,reversal,StartupState.ACTIVE,1,eligible,List.of());}
}
