package com.crypto.laplace.execution;
import static org.mockito.Mockito.*;import static org.assertj.core.api.Assertions.assertThat;import com.crypto.common.enums.PositionSide;import com.crypto.laplace.config.LaplaceStrategyProperties;import com.crypto.laplace.model.*;import com.crypto.laplace.persistence.*;import java.time.Instant;import java.util.*;import org.junit.jupiter.api.BeforeEach;import org.junit.jupiter.api.Test;
class LaplacePaperTradeCoordinatorTest {
 LaplacePaperPositionRepository repo=mock(LaplacePaperPositionRepository.class);LaplacePaperExecutionService execution=mock(LaplacePaperExecutionService.class);LaplaceTradeJsonlWriter writer=mock(LaplaceTradeJsonlWriter.class);com.crypto.laplace.service.LaplaceDiagnosticLogService diagnostics=mock(com.crypto.laplace.service.LaplaceDiagnosticLogService.class);com.crypto.laplace.service.LaplaceTrueSymbolStopLossCooldownService cooldown=mock(com.crypto.laplace.service.LaplaceTrueSymbolStopLossCooldownService.class);LaplaceStrategyProperties config=new LaplaceStrategyProperties();LaplacePaperTradeCoordinator coordinator;
 @BeforeEach void setup(){config.getLaplace().setPaperExecutionEnabled(true);var runtime=mock(com.crypto.laplace.service.LaplaceRuntimeService.class);when(runtime.isActive()).thenReturn(true);coordinator=new LaplacePaperTradeCoordinator(config,repo,execution,writer,runtime,diagnostics,cooldown);}
 @Test void mapsRawSignalsContrarian(){assertThat(coordinator.mapRawSignalToExecutionSide(LaplaceSignal.LONG)).isEqualTo(PositionSide.SHORT);assertThat(coordinator.mapRawSignalToExecutionSide(LaplaceSignal.SHORT)).isEqualTo(PositionSide.LONG);assertThat(coordinator.mapRawSignalToExecutionSide(LaplaceSignal.NONE)).isNull();}
 @Test void startupBaselineSameSignalDoesNotOpen(){coordinator.initializeBaseline("BTCUSDT",LaplaceSignal.LONG);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.NONE,true),true);verifyNoInteractions(execution);}
 @Test void flatLongOpensExactlyOnce(){when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of());when(execution.open(any(),eq(PositionSide.SHORT),isNull(),eq("FLAT"))).thenReturn(position(PositionSide.SHORT));coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.NONE,true),true);verify(execution).open(any(),eq(PositionSide.SHORT),isNull(),eq("FLAT"));}
 @Test void ineligibleSignalDoesNotOpen(){coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.NONE,false),true);verifyNoInteractions(execution);}
 @Test void paperDisabledDoesNotOpenOrWritePerSignalFailures(){config.getLaplace().setPaperExecutionEnabled(false);coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.NONE,true),true);coordinator.onSignal(signal(LaplaceSignal.SHORT,LaplaceSignal.NONE,true),true);verifyNoInteractions(execution,writer);}
 @Test void sameSideSignalDoesNotPyramid(){when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of(position(PositionSide.LONG)));coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.SHORT,LaplaceSignal.SHORT,true),true);verifyNoInteractions(execution);}
 @Test void strongOppositeReversesButNormalEntryDoesNot(){var p=position(PositionSide.LONG);when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of(p));coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.SHORT,LaplaceSignal.NONE,true),true);verifyNoInteractions(execution);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.LONG,true),true);verify(execution).reverse(any(),eq(p),eq(PositionSide.SHORT),eq(true),eq(false));}
 @Test void outsideUniverseClosesWithoutOpeningTarget(){var p=position(PositionSide.LONG);when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of(p));coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.LONG,true),false);verify(execution).reverse(any(),eq(p),eq(PositionSide.SHORT),eq(false),eq(false));}
 @Test void activeSymbolCooldownBlocksEntryAndLogs(){var active=new com.crypto.laplace.service.LaplaceTrueSymbolStopLossCooldownService.ActiveCooldown("sl",Instant.now(),Instant.now(),Instant.now().plusSeconds(14400));when(cooldown.active("BTCUSDT")).thenReturn(Optional.of(active));when(cooldown.remainingSeconds(active)).thenReturn(14400L);when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of());coordinator.initializeBaseline("BTCUSDT",LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.NONE,true,1.0,.01),true);verify(execution,never()).open(any(),any(),any(),any());verify(diagnostics).trueSymbolStopLossCooldown(any(),eq(PositionSide.SHORT),eq(1.0),eq(.01),same(active),eq(14400L));}
 @Test void activeSymbolCooldownClosesReversalWithoutReplacement(){var p=position(PositionSide.LONG);var now=Instant.now();var active=new com.crypto.laplace.service.LaplaceTrueSymbolStopLossCooldownService.ActiveCooldown("sl",now,now,now.plusSeconds(14400));when(cooldown.active("BTCUSDT")).thenReturn(Optional.of(active));when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of(p));coordinator.initializeBaseline("BTCUSDT",LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.LONG,true,1.0,.01),true);verify(execution).reverse(any(),same(p),eq(PositionSide.SHORT),eq(false),eq(true));}
 @Test void exactSoftFilterBoundaryBlocksEntryWithoutSideEffects(){assertBlocked(5.0,.16);verifyNoInteractions(execution,writer);verify(diagnostics).trueSoftRiskFilter(any(),eq(PositionSide.SHORT),eq(5.0),eq(.16),eq(5.0),eq(.16));}
 @Test void insideSoftFilterBandBlocksEntry(){assertBlocked(6.0,.20);verifyNoInteractions(execution,writer);}
 @Test void atrBelowThresholdAllowsEntry(){assertAllowed(4.99,.80);}
 @Test void slopeBelowThresholdAllowsEntry(){assertAllowed(8.0,.159);}
 @Test void highSlopeHasNoUpperExemption(){assertBlocked(5.0,.30);}
 @Test void reversalClosesWithoutFilteredReplacement(){var p=position(PositionSide.LONG);when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of(p));coordinator.initializeBaseline("BTCUSDT",LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.LONG,true,6.0,.20),true);verify(execution).reverse(any(),eq(p),eq(PositionSide.SHORT),eq(false),eq(true));verify(execution,never()).open(any(),any(),any(),any());}
 private void assertBlocked(double atr,double slope){when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of());coordinator.initializeBaseline("BTCUSDT",LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.NONE,true,atr,slope),true);verify(execution,never()).open(any(),any(),any(),any());}
 private void assertAllowed(double atr,double slope){when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of());coordinator.initializeBaseline("BTCUSDT",LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.NONE,true,atr,slope),true);verify(execution).open(any(),eq(PositionSide.SHORT),isNull(),eq("FLAT"));}
 private LaplacePaperPositionEntity position(PositionSide side){return LaplacePaperPositionEntity.builder().id("id").symbol("BTCUSDT").side(side).strategy(LaplacePaperExecutionService.STRATEGY).status(LaplacePositionStatus.OPEN).build();}
 private LaplaceSignalResult signal(LaplaceSignal entry,LaplaceSignal reversal,boolean eligible){Instant now=Instant.now();return new LaplaceSignalResult(LaplacePaperExecutionService.STRATEGY,"1.0","BTCUSDT","30m","LAPLACE",14,"CLOSE",false,now.minusSeconds(1800),now,100,99,98,97,1,1,10,10,.1,.1,.03,.04,2,entry,reversal,StartupState.ACTIVE,1,eligible,List.of());}
 private LaplaceSignalResult signal(LaplaceSignal entry,LaplaceSignal reversal,boolean eligible,double atrPercentage,double slope){Instant now=Instant.now();return new LaplaceSignalResult(LaplacePaperExecutionService.STRATEGY,"1.0","BTCUSDT","30m","LAPLACE",14,"CLOSE",false,now.minusSeconds(1800),now,100,99,98,97,1,1,atrPercentage,10,slope,.1,.03,.04,2,entry,reversal,StartupState.ACTIVE,1,eligible,List.of());}
}
