package com.crypto.laplace.execution;
import static org.mockito.Mockito.*;import static org.assertj.core.api.Assertions.assertThat;import com.crypto.common.enums.PositionSide;import com.crypto.laplace.config.LaplaceStrategyProperties;import com.crypto.laplace.model.*;import com.crypto.laplace.persistence.*;import com.crypto.laplace.service.*;import com.crypto.laplace.session.LaplaceSessionManager;import java.time.Instant;import java.util.*;import org.junit.jupiter.api.BeforeEach;import org.junit.jupiter.api.Test;
class LaplacePaperTradeCoordinatorTest {
 LaplacePaperPositionRepository repo=mock(LaplacePaperPositionRepository.class);LaplacePaperExecutionService execution=mock(LaplacePaperExecutionService.class);LaplaceTradeJsonlWriter writer=mock(LaplaceTradeJsonlWriter.class);LaplaceStrategyProperties config=new LaplaceStrategyProperties();LaplaceEntryDecisionService decisions=mock(LaplaceEntryDecisionService.class);LaplaceDiagnosticLogService diagnostics=mock(LaplaceDiagnosticLogService.class);LaplacePositionManagementService management=mock(LaplacePositionManagementService.class);LaplaceSessionManager session=mock(LaplaceSessionManager.class);LaplacePaperTradeCoordinator coordinator;
 @BeforeEach void setup(){config.getLaplace().setPaperExecutionEnabled(true);when(session.currentSessionId()).thenReturn("session");when(session.processSignal(any(),any())).thenAnswer(call->{call.getArgument(1,Runnable.class).run();return true;});when(session.allowEntry(any(),any(),any(),any(),anyMap(),anyBoolean(),anyInt())).thenReturn(true);when(session.executeEntry(any(),any(),any(),any(),anyMap(),anyBoolean(),anyInt(),any())).thenAnswer(call->{call.getArgument(7,Runnable.class).run();return true;});when(decisions.evaluate(any(),any())).thenReturn(new LaplaceEntryDecision(true,PositionSide.SHORT,0,0,0,0,0,0,0,0,0,0,24,36,0,1,0,1,0,0,0,0,0,false,List.of()));coordinator=new LaplacePaperTradeCoordinator(config,repo,execution,writer,decisions,diagnostics,management,session);}
 @Test void mapsRawSignalsContrarian(){assertThat(coordinator.mapRawSignalToExecutionSide(LaplaceSignal.LONG)).isEqualTo(PositionSide.SHORT);assertThat(coordinator.mapRawSignalToExecutionSide(LaplaceSignal.SHORT)).isEqualTo(PositionSide.LONG);assertThat(coordinator.mapRawSignalToExecutionSide(LaplaceSignal.NONE)).isNull();}
 @Test void startupBaselineSameSignalDoesNotOpen(){coordinator.initializeBaseline("BTCUSDT",LaplaceSignal.LONG);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.NONE,true),true);verify(execution,never()).open(any(),any(),any(),any(),any());verify(execution,never()).closeForOppositeSignal(any(),any(),any());verify(execution,never()).closeStrongSignalBugfix(any(),any());}
 @Test void flatLongOpensExactlyOnce(){when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of());when(execution.open(any(),eq(PositionSide.SHORT),isNull(),eq("FLAT"),any())).thenReturn(position(PositionSide.SHORT));coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.NONE,true),true);verify(execution).open(any(),eq(PositionSide.SHORT),isNull(),eq("FLAT"),any());}
 @Test void ineligibleSignalDoesNotOpen(){coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.NONE,false),true);verifyNoInteractions(execution);}
 @Test void paperDisabledDoesNotOpenOrWritePerSignalFailures(){config.getLaplace().setPaperExecutionEnabled(false);coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.NONE,true),true);coordinator.onSignal(signal(LaplaceSignal.SHORT,LaplaceSignal.NONE,true),true);verifyNoInteractions(execution,writer);}
 @Test void sameSideSignalDoesNotPyramid(){when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of(position(PositionSide.LONG)));coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.SHORT,LaplaceSignal.SHORT,true),true);verify(execution,never()).open(any(),any(),any(),any(),any());verify(execution,never()).closeForOppositeSignal(any(),any(),any());}
 @Test void strongOppositeReversesButNormalEntryDoesNot(){var p=position(PositionSide.LONG);when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of(p));when(execution.closeForOppositeSignal(any(),eq(p),any())).thenReturn(new LaplacePaperExecutionService.SignalCloseOutcome(p,"r"));coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.SHORT,LaplaceSignal.NONE,true),true);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.LONG,true),true);verify(execution).closeForOppositeSignal(any(),eq(p),eq(PositionSide.SHORT));}
 @Test void outsideUniverseClosesWithoutOpeningTarget(){var p=position(PositionSide.LONG);when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of(p));when(execution.closeForOppositeSignal(any(),eq(p),any())).thenReturn(new LaplacePaperExecutionService.SignalCloseOutcome(p,"r"));coordinator.initializeBaseline("BTCUSDT", LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.LONG,true),false);verify(execution).closeForOppositeSignal(any(),eq(p),eq(PositionSide.SHORT));}

 @Test void nonFreshStrongOppositeEffectiveClosesOpenShort(){var p=position(PositionSide.SHORT);when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of(p));coordinator.initializeBaseline("BTCUSDT",LaplaceSignal.SHORT);coordinator.onSignal(signal(LaplaceSignal.SHORT,LaplaceSignal.SHORT,true),true);verify(execution).closeStrongSignalBugfix(any(),eq(p));}
 @Test void nonFreshStrongSameEffectiveDoesNotCloseOpenShort(){var p=position(PositionSide.SHORT);when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of(p));coordinator.initializeBaseline("BTCUSDT",LaplaceSignal.SHORT);coordinator.onSignal(signal(LaplaceSignal.SHORT,LaplaceSignal.LONG,true),true);verify(execution,never()).closeStrongSignalBugfix(any(),any());}
 @Test void freshReversalStillClosesAndOpensTarget(){var p=position(PositionSide.SHORT);when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of(p));when(execution.closeForOppositeSignal(any(),eq(p),eq(PositionSide.LONG))).thenReturn(new LaplacePaperExecutionService.SignalCloseOutcome(p,"r"));coordinator.initializeBaseline("BTCUSDT",LaplaceSignal.LONG);coordinator.onSignal(signal(LaplaceSignal.SHORT,LaplaceSignal.SHORT,true),true);verify(execution).closeForOppositeSignal(any(),eq(p),eq(PositionSide.LONG));verify(execution).open(any(),eq(PositionSide.LONG),eq("r"),eq("SHORT"),any());verify(execution,never()).closeStrongSignalBugfix(any(),any());}

 @Test void shortClosedDuringCatchUpIsNotReopenedSameCycle(){var p=position(PositionSide.SHORT);when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of(p),List.of(p),List.of());when(management.catchUp("id",any())).thenReturn(new PositionCatchUpResult(1,true,Instant.now()));coordinator.initializeBaseline("BTCUSDT",LaplaceSignal.NONE);coordinator.onSignal(signal(LaplaceSignal.LONG,LaplaceSignal.NONE,true),true);verify(execution,never()).open(any(),eq(PositionSide.SHORT),any(),any(),any());}
 @Test void staleSessionSignalCannotMutateCoordinatorOrTrade(){reset(session);when(session.processSignal(eq("old"),any())).thenReturn(false);coordinator.onSignal(signal(LaplaceSignal.SHORT,LaplaceSignal.SHORT,true),true,"old",Map.of("BTCUSDT",new java.math.BigDecimal("30000000")));assertThat(coordinator.rawStateCount()).isZero();assertThat(coordinator.strongExitStateCount()).isZero();verifyNoInteractions(execution,management);}
 @Test void batchSelectsHighestScoredFiveLongsRegardlessOfInputOrder(){when(repo.findByStrategyAndSymbolAndStatus(any(),any(),any())).thenReturn(List.of());when(decisions.evaluate(any(),eq(PositionSide.LONG))).thenAnswer(call->{LaplaceSignalResult s=call.getArgument(0);double q=Integer.parseInt(s.symbol().substring(1));return new LaplaceEntryDecision(true,PositionSide.LONG,0,q,2*q,0,0,0,0,0,0,0,24,36,0,q,q,q,q,q,0,-q,0,false,List.of());});List<LaplacePaperTradeCoordinator.SignalEnvelope> batch=new ArrayList<>();Map<String,java.math.BigDecimal> volumes=new HashMap<>();for(int i=0;i<12;i++){String symbol="S"+i;coordinator.initializeBaseline(symbol,LaplaceSignal.NONE);batch.add(new LaplacePaperTradeCoordinator.SignalEnvelope(signal(symbol,LaplaceSignal.SHORT),true));volumes.put(symbol,new java.math.BigDecimal("30000000"));}Collections.reverse(batch);coordinator.onSignalBatch(batch,"session",volumes);var captor=org.mockito.ArgumentCaptor.forClass(LaplaceSignalResult.class);verify(execution,times(5)).open(captor.capture(),eq(PositionSide.LONG),any(),any(),any());assertThat(captor.getAllValues()).extracting(LaplaceSignalResult::symbol).containsExactlyInAnyOrder("S7","S8","S9","S10","S11");}
 private LaplacePaperPositionEntity position(PositionSide side){return LaplacePaperPositionEntity.builder().id("id").symbol("BTCUSDT").side(side).strategy(LaplacePaperExecutionService.STRATEGY).status(LaplacePositionStatus.OPEN).build();}
 private LaplaceSignalResult signal(LaplaceSignal entry,LaplaceSignal reversal,boolean eligible){Instant now=Instant.now();return new LaplaceSignalResult(LaplacePaperExecutionService.STRATEGY,"1.0","BTCUSDT","30m","LAPLACE",14,"CLOSE",false,now.minusSeconds(1800),now,100,99,98,97,1,1,10,10,.1,.1,.03,.04,2,entry,reversal,StartupState.ACTIVE,1,eligible,List.of());}
 private LaplaceSignalResult signal(String symbol,LaplaceSignal entry){Instant now=Instant.parse("2026-01-01T00:30:00Z");return new LaplaceSignalResult(LaplacePaperExecutionService.STRATEGY,"1.0",symbol,"30m","LAPLACE",14,"CLOSE",false,now.minusSeconds(1800),now,100,99,98,97,1,1,10,10,.1,.1,.03,.04,2,entry,LaplaceSignal.NONE,StartupState.ACTIVE,1,true,List.of());}
}
