package com.crypto.laplace.execution;
import com.crypto.laplace.config.LaplaceStrategyProperties;import com.crypto.laplace.persistence.*;import com.fasterxml.jackson.databind.ObjectMapper;import java.nio.file.*;import java.time.Instant;import java.util.*;import lombok.RequiredArgsConstructor;import lombok.extern.slf4j.Slf4j;import org.springframework.boot.ApplicationArguments;import org.springframework.boot.ApplicationRunner;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Slf4j @Service @RequiredArgsConstructor
public class LaplaceTradeJsonlWriter implements ApplicationRunner {
 private final LaplaceTradeEventRepository repository;private final ObjectMapper mapper;private final LaplaceStrategyProperties properties;
 @Override public void run(ApplicationArguments args){drain();}
 @Transactional public synchronized void drain(){for(var event:repository.findTop100ByJsonlWrittenFalseOrderByCreatedAtAsc())try{Path dir=Path.of(properties.getLaplace().getDiagnosticDirectory());Files.createDirectories(dir);Path file=dir.resolve("laplace-trades-"+java.time.LocalDate.now()+".jsonl");String existing=Files.exists(file)?Files.readString(file):"";if(!existing.contains("\"eventId\":\""+event.getEventId()+"\""))Files.writeString(file,event.getPayloadJson()+System.lineSeparator(),StandardOpenOption.CREATE,StandardOpenOption.APPEND);event.setJsonlWritten(true);event.setWrittenAt(Instant.now());repository.save(event);}catch(Exception e){log.error("JSONL_WRITE_FAILED eventId={} symbol={} errorMessage={}",event.getEventId(),event.getSymbol(),e.getMessage());return;}}
 public String json(Object value){try{return mapper.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException("JSON serialization failed",e);}}
 @Transactional public void failure(String symbol,Instant candle,String currentPosition,String action,String reason,Throwable error,boolean retryable){String id=UUID.randomUUID().toString();Map<String,Object> payload=new LinkedHashMap<>();payload.put("eventType","FAILURE");payload.put("eventId",id);payload.put("strategy",LaplacePaperExecutionService.STRATEGY);payload.put("symbol",symbol);payload.put("signalCandleCloseTime",candle);payload.put("currentPosition",currentPosition);payload.put("requestedAction",action);payload.put("failureReason",reason);payload.put("errorType",error==null?null:error.getClass().getSimpleName());payload.put("errorMessage",error==null?null:error.getMessage());payload.put("retryable",retryable);repository.save(LaplaceTradeEventEntity.builder().eventId(id).eventType("FAILURE").symbol(symbol).payloadJson(json(payload)).jsonlWritten(false).createdAt(Instant.now()).build());}
}
