package com.crypto.laplace.execution;

import com.crypto.common.enums.PositionSide;
import com.crypto.laplace.config.LaplaceStrategyProperties;
import com.crypto.laplace.model.*;
import com.crypto.laplace.persistence.*;
import com.crypto.laplace.service.LaplaceDiagnosticLogService;
import com.crypto.laplace.service.LaplaceEntryDecisionService;
import com.crypto.laplace.service.LaplacePositionManagementService;
import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicBoolean;import java.util.concurrent.locks.ReentrantLock;
import lombok.RequiredArgsConstructor;import lombok.extern.slf4j.Slf4j;import org.springframework.stereotype.Service;
import com.crypto.laplace.session.LaplaceSessionManager;

/** Keeps raw strategy signals untouched and applies the contrarian mapping only at execution. */
@Slf4j @Service @RequiredArgsConstructor
public class LaplacePaperTradeCoordinator {
 private final LaplaceStrategyProperties config;private final LaplacePaperPositionRepository positions;private final LaplacePaperExecutionService execution;private final LaplaceTradeJsonlWriter writer;private final LaplaceEntryDecisionService entryDecisionService;private final LaplaceDiagnosticLogService diagnostics;private final LaplacePositionManagementService management;private final LaplaceSessionManager session;private final ConcurrentHashMap<String,ReentrantLock> locks=new ConcurrentHashMap<>();private final ConcurrentHashMap<String,LaplaceSignal> rawStates=new ConcurrentHashMap<>();private final ConcurrentHashMap<String,java.time.Instant> strongExitCandles=new ConcurrentHashMap<>();private final AtomicBoolean paperDisabledLogged=new AtomicBoolean(false);
 public void clearSessionRuntime(){rawStates.clear();strongExitCandles.clear();paperDisabledLogged.set(false);}
 public Set<String> managementSymbols(){Set<String>x=new HashSet<>();for(var p:positions.findByStrategyAndTradingRunIdAndStatus(LaplacePaperExecutionService.STRATEGY,session.tradingRunId(),LaplacePositionStatus.OPEN))x.add(p.getSymbol());return Set.copyOf(x);}
 public PositionSide mapRawSignalToExecutionSide(LaplaceSignal raw){return switch(raw){case LONG->PositionSide.SHORT;case SHORT->PositionSide.LONG;case NONE->null;};}
 /** Startup history establishes a raw baseline only; it deliberately never executes. */
 public void initializeBaseline(String symbol,LaplaceSignal raw){rawStates.put(symbol,raw);log.info("LAPLACE_STARTUP_RAW_BASELINE_INITIALIZED symbol={} startupRawSignalState={}",symbol,raw);}
 public void onSignal(LaplaceSignalResult signal,boolean inEntryUniverse){
  onSignal(signal,inEntryUniverse,session.currentSessionId(),Map.of());
 }
 public void onSignal(LaplaceSignalResult signal,boolean inEntryUniverse,String scanSessionId,Map<String,java.math.BigDecimal> currentVolumes){
  session.processSignal(scanSessionId,()->processSignal(signal,inEntryUniverse,scanSessionId,currentVolumes));
 }
 public void onSignalBatch(List<SignalEnvelope> batch,String scanSessionId,Map<String,java.math.BigDecimal> currentVolumes){
  session.processSignal(scanSessionId,()->{List<PendingEntry> pending=new ArrayList<>();for(SignalEnvelope item:batch)processSignal(item.signal(),item.inEntryUniverse(),scanSessionId,currentVolumes,pending);executeRanked(pending,scanSessionId,currentVolumes);});
 }
 private void processSignal(LaplaceSignalResult signal,boolean inEntryUniverse,String scanSessionId,Map<String,java.math.BigDecimal> currentVolumes){processSignal(signal,inEntryUniverse,scanSessionId,currentVolumes,null);}
 private void processSignal(LaplaceSignalResult signal,boolean inEntryUniverse,String scanSessionId,Map<String,java.math.BigDecimal> currentVolumes,List<PendingEntry> pending){
  if(signal==null||signal.startupState()!=StartupState.ACTIVE||signal.postStartupClosedBarCount()<1)return;
  if(!config.getLaplace().isPaperExecutionEnabled()){if(signal.entrySignal()!=LaplaceSignal.NONE&&paperDisabledLogged.compareAndSet(false,true))log.warn("LAPLACE_PAPER_EXECUTION_DISABLED strategy={} symbol={}",LaplacePaperExecutionService.STRATEGY,signal.symbol());return;}
  ReentrantLock lock=locks.computeIfAbsent(signal.symbol(),s->new ReentrantLock());lock.lock();try {LaplaceSignal previous=rawStates.put(signal.symbol(),signal.entrySignal());if(previous==null){log.info("LAPLACE_STARTUP_RAW_BASELINE_INITIALIZED symbol={} startupRawSignalState={}",signal.symbol(),signal.entrySignal());return;}boolean fresh=previous!=signal.entrySignal();PositionSide effective=mapRawSignalToExecutionSide(signal.entrySignal());log.info("LAPLACE_FRESH_SIGNAL rawSignal={} effectiveExecutionSide={} previousRawState={} currentRawState={} isFreshSignal={} currentPosition={} requestedAction={}",signal.entrySignal(),effective,previous,signal.entrySignal(),fresh,current(signal.symbol()),fresh&&effective!=null?"EVALUATE":"NONE");PositionSide fastClosedSide=catchUpAndLongFastExit(signal);if(fresh){if(fastClosedSide!=effective)coordinate(signal,inEntryUniverse,effective,scanSessionId,currentVolumes,pending);return;}evaluateMissedStrongExitBugfix(signal);}finally{lock.unlock();}
 }

 private PositionSide catchUpAndLongFastExit(LaplaceSignalResult signal){
  List<LaplacePaperPositionEntity> open=positions.findByStrategyAndTradingRunIdAndSymbolAndStatus(LaplacePaperExecutionService.STRATEGY,session.tradingRunId(),signal.symbol(),LaplacePositionStatus.OPEN);if(open.size()!=1)return null;PositionSide sideBeforeCatchUp=open.getFirst().getSide();PositionCatchUpResult catchUp=management.catchUp(open.getFirst().getId(),signal.signalCandleCloseTime());open=positions.findByStrategyAndTradingRunIdAndSymbolAndStatus(LaplacePaperExecutionService.STRATEGY,session.tradingRunId(),signal.symbol(),LaplacePositionStatus.OPEN);if((catchUp!=null&&catchUp.positionClosed())||open.isEmpty())return sideBeforeCatchUp;if(open.size()==1&&execution.closeLongFastRegime(signal,open.getFirst())){writer.drain();return sideBeforeCatchUp;}return null;
 }
 private void evaluateMissedStrongExitBugfix(LaplaceSignalResult signal){
  if(signal.strongReversalSignal()==LaplaceSignal.NONE)return;List<LaplacePaperPositionEntity> open=positions.findByStrategyAndTradingRunIdAndSymbolAndStatus(LaplacePaperExecutionService.STRATEGY,session.tradingRunId(),signal.symbol(),LaplacePositionStatus.OPEN);if(open.size()!=1)return;java.time.Instant prior=strongExitCandles.put(signal.symbol(),signal.signalCandleCloseTime());if(signal.signalCandleCloseTime().equals(prior))return;LaplacePaperPositionEntity p=open.getFirst();PositionSide strongEffective=mapRawSignalToExecutionSide(signal.strongReversalSignal());if(strongEffective!=null&&strongEffective!=p.getSide()){execution.closeStrongSignalBugfix(signal,p);writer.drain();log.info("EXIT_STRONG_SIGNAL_BUGFIX symbol={} candle={}",signal.symbol(),signal.signalCandleCloseTime());}
 }
 private String current(String symbol){var x=positions.findByStrategyAndTradingRunIdAndSymbolAndStatus(LaplacePaperExecutionService.STRATEGY,session.tradingRunId(),symbol,LaplacePositionStatus.OPEN);return x.isEmpty()?"FLAT":x.getFirst().getSide().name();}
 private void coordinate(LaplaceSignalResult signal,boolean inEntryUniverse,PositionSide effective,String scanSessionId,Map<String,java.math.BigDecimal> currentVolumes,List<PendingEntry> pending){
  List<LaplacePaperPositionEntity> open=positions.findByStrategyAndTradingRunIdAndSymbolAndStatus(LaplacePaperExecutionService.STRATEGY,session.tradingRunId(),signal.symbol(),LaplacePositionStatus.OPEN);if(open.size()>1){failure(signal,"CONFLICT","NONE","POSITION_STATE_CONFLICT",null,false);return;}
  if(open.isEmpty()){if(effective==null||!signal.eligibleForExecution())return;if(!inEntryUniverse){failure(signal,"FLAT","ENTRY","SYMBOL_OUTSIDE_ENTRY_UNIVERSE",null,false);return;}var decision=entryDecisionService.evaluate(signal,effective);diagnostics.entryDecision(signal,decision);if(!decision.allowed())return;if(pending!=null){if(session.allowEntry(scanSessionId,signal.symbol(),effective,signal.signalCandleCloseTime(),currentVolumes,true,0))pending.add(new PendingEntry(signal,effective,decision,null,"FLAT"));return;}try{session.executeEntry(scanSessionId,signal.symbol(),effective,signal.signalCandleCloseTime(),currentVolumes,true,0,()->execution.open(signal,effective,null,"FLAT",decision));writer.drain();}catch(RuntimeException e){failure(signal,"FLAT","ENTRY",reason(e,"ENTRY_EXECUTION_FAILED"),e,true);}return;}
  LaplacePaperPositionEntity p=open.getFirst();if(effective==null||p.getSide()==effective){log.info("LAPLACE_SAME_EFFECTIVE_SIDE_SIGNAL_IGNORED symbol={} side={}",signal.symbol(),p.getSide());return;}
  PositionSide reversalTarget=mapRawSignalToExecutionSide(signal.strongReversalSignal());if(reversalTarget==null||reversalTarget!=effective)return;
  try{List<LaplacePaperPositionEntity> stillOpen=positions.findByStrategyAndTradingRunIdAndSymbolAndStatus(LaplacePaperExecutionService.STRATEGY,session.tradingRunId(),signal.symbol(),LaplacePositionStatus.OPEN);boolean closedDuringCatchUp=stillOpen.isEmpty();String reversalId=null;if(!closedDuringCatchUp){var outcome=execution.closeForOppositeSignal(signal,stillOpen.getFirst(),effective);reversalId=outcome.reversalId();writer.drain();}if(!inEntryUniverse)return;var decision=entryDecisionService.evaluate(signal,effective);diagnostics.entryDecision(signal,decision);if(!decision.allowed())return;if(pending!=null){if(session.allowEntry(scanSessionId,signal.symbol(),effective,signal.signalCandleCloseTime(),currentVolumes,true,0))pending.add(new PendingEntry(signal,effective,decision,reversalId,closedDuringCatchUp?"FLAT":p.getSide().name()));return;}String finalReversalId=reversalId;session.executeEntry(scanSessionId,signal.symbol(),effective,signal.signalCandleCloseTime(),currentVolumes,true,0,()->execution.open(signal,effective,finalReversalId,closedDuringCatchUp?"FLAT":p.getSide().name(),decision));writer.drain();}catch(RuntimeException e){failure(signal,p.getSide().name(),"REVERSAL",reason(e,"REVERSAL_CLOSE_FAILED"),e,true);}
 }
 private void executeRanked(List<PendingEntry> pending,String sessionId,Map<String,java.math.BigDecimal> volumes){
  for(PendingEntry x:pending.stream().filter(p->p.side()!=PositionSide.LONG).toList())executeCandidate(x,sessionId,volumes,0,Double.NaN,0,true);
  Map<java.time.Instant,List<PendingEntry>> slots=new TreeMap<>();for(PendingEntry x:pending)if(x.side()==PositionSide.LONG)slots.computeIfAbsent(x.signal().signalCandleCloseTime(),k->new ArrayList<>()).add(x);
  for(var slot:slots.entrySet()){List<PendingEntry> longs=slot.getValue();Map<PendingEntry,Double> scores=compositeScores(longs);List<PendingEntry> ranked=longs.stream().sorted(Comparator.<PendingEntry>comparingDouble(scores::get).reversed().thenComparing(x->x.signal().symbol())).toList();int selectedCount=Math.min(config.getLaplace().getMaxLongPerThirtyMinuteSlot(),ranked.size());Set<PendingEntry> selected=new HashSet<>(ranked.subList(0,selectedCount));for(PendingEntry x:ranked)executeCandidate(x,sessionId,volumes,ranked.indexOf(x)+1,scores.get(x),ranked.size(),selected.contains(x));}
 }
 private void executeCandidate(PendingEntry x,String sessionId,Map<String,java.math.BigDecimal> volumes,int rank,double score,int candidateCount,boolean selected){log.info("LAPLACE_LONG_BATCH_DECISION symbol={} signal30mSlot={} longCandidateCountInSlot={} longCandidateRank={} longCandidateScore={} longSelectedInSlot={} reason={}",x.signal().symbol(),x.signal().signalCandleCloseTime(),candidateCount,rank,score,Math.min(candidateCount,config.getLaplace().getMaxLongPerThirtyMinuteSlot()),selected?"SELECTED":LaplaceSessionManager.LONG_CAP_REASON);if(!selected)return;try{session.executeEntry(sessionId,x.signal().symbol(),x.side(),x.signal().signalCandleCloseTime(),volumes,true,candidateCount,()->execution.open(x.signal(),x.side(),x.reversalId(),x.positionBefore(),x.decision()));writer.drain();}catch(RuntimeException e){failure(x.signal(),x.positionBefore(),"ENTRY",reason(e,"ENTRY_EXECUTION_FAILED"),e,true);}}
 private Map<PendingEntry,Double> compositeScores(List<PendingEntry> xs){Map<PendingEntry,Double> result=new HashMap<>();double atrThreshold=config.getLaplace().getLongAtrThreshold().doubleValue(),distanceThreshold=config.getLaplace().getLongDistanceFromLowThresholdPct().doubleValue();for(PendingEntry x:xs)result.put(x,rank(xs,x,p->p.decision().volumeProfileGapPct())+rank(xs,x,p->Math.max(Math.max(0d,(atrThreshold-p.decision().atrPercentage30m())/atrThreshold),Math.max(0d,(distanceThreshold-p.decision().distanceFromLowestLow24Pct())/distanceThreshold)))+rank(xs,x,p->Math.max(Math.max(0d,(.30d-p.decision().rangePosition2h())/.30d),Math.max(0d,(p.decision().quoteVolumeAccel1h()-.90d)/.90d)))+rank(xs,x,p->Math.max(p.decision().momentumDeteriorationPct()-(-.20d),p.decision().green5mCandleCountLast30m()-1d))+rank(xs,x,p->Math.min(Math.abs(p.signal().currentNormalizedSlope()),Math.abs(p.signal().previousNormalizedSlope()))));return result;}
 private double rank(List<PendingEntry> xs,PendingEntry target,java.util.function.ToDoubleFunction<PendingEntry> metric){double value=metric.applyAsDouble(target);long below=xs.stream().filter(x->metric.applyAsDouble(x)<value).count();return xs.size()<2?1d:(double)below/(xs.size()-1);}
 public int rawStateCount(){return rawStates.size();}public int strongExitStateCount(){return strongExitCandles.size();}
 public record SignalEnvelope(LaplaceSignalResult signal,boolean inEntryUniverse){}
 private record PendingEntry(LaplaceSignalResult signal,PositionSide side,LaplaceEntryDecision decision,String reversalId,String positionBefore){}
 private void failure(LaplaceSignalResult s,String current,String action,String reason,Throwable e,boolean retry){writer.failure(s.symbol(),s.signalCandleCloseTime(),current,action,reason,e,retry);writer.drain();}
 private String reason(RuntimeException e,String fallback){return e.getMessage()!=null&&Set.of("EXECUTION_PRICE_UNAVAILABLE","INVALID_QUANTITY","INVALID_NOTIONAL","POSITION_STATE_CONFLICT","DUPLICATE_EXECUTION_BLOCKED","REVERSAL_OPEN_FAILED","INSUFFICIENT_PAPER_BALANCE").contains(e.getMessage())?e.getMessage():fallback;}
}
