package com.crypto.laplace.execution;

import com.crypto.common.enums.PositionSide;
import com.crypto.laplace.model.*;
import com.crypto.laplace.persistence.*;
import com.crypto.laplace.service.StartupMarketUniverseService;
import com.crypto.laplace.config.LaplaceStrategyProperties;
import java.math.*;import java.time.*;import java.util.*;
import lombok.RequiredArgsConstructor;import lombok.extern.slf4j.Slf4j;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Slf4j @Service @RequiredArgsConstructor
public class LaplacePaperExecutionService {
 public static final String STRATEGY="LAPLACE_KERNEL_REGRESSION_30M", VERSION="1.0";private static final int SCALE=12;
 private final LaplacePaperPositionRepository positions;private final LaplaceTradeEventRepository events;private final LaplaceExecutionPriceProvider prices;private final LaplacePnlCalculator pnl;private final LaplaceStrategyProperties properties;private final LaplaceTradeJsonlWriter writer;
 private final StartupMarketUniverseService universe;
 @Transactional public LaplacePaperPositionEntity open(LaplaceSignalResult signal,PositionSide side,String reversalId,String positionBefore){
  assertNoOpen(signal.symbol());MarketExecutionAction action=side==PositionSide.LONG?MarketExecutionAction.LONG_OPEN:MarketExecutionAction.SHORT_OPEN;var quote=prices.quote(signal.symbol(),action);Instant requested=Instant.now();BigDecimal price=quote.value();BigDecimal notional=properties.getLaplace().getNotionalUsdt();int leverage=properties.getLaplace().getLeverage();BigDecimal margin=properties.getLaplace().getMarginPerPositionUsdt();BigDecimal quantity=notional.divide(price,SCALE,RoundingMode.DOWN);BigDecimal feeRate=properties.getLaplace().getTakerFeeRate();
  if(quantity.signum()<=0)throw new IllegalStateException("INVALID_QUANTITY");if(!hasAvailableBalance(margin.add(notional.multiply(feeRate))))throw new IllegalStateException("INSUFFICIENT_PAPER_BALANCE");BigDecimal fee=notional.multiply(feeRate).setScale(SCALE,RoundingMode.HALF_UP);String signalId=entryKey(signal,side);Instant now=Instant.now();
  var p=LaplacePaperPositionEntity.builder().id(UUID.randomUUID().toString()).strategy(STRATEGY).strategyVersion(VERSION).symbol(signal.symbol()).side(side).status(LaplacePositionStatus.OPEN).entrySignalId(signalId).entryRawSignal(signal.entrySignal().name()).signalInverted(true).entryCandleCloseTime(signal.signalCandleCloseTime()).entryTime(now).entrySignalClosePrice(BigDecimal.valueOf(signal.signalCandleClose())).entryExecutionPrice(price).margin(margin).quantity(quantity).notional(notional).leverage(leverage).entryFeeRate(feeRate).entryFee(fee).build();positions.saveAndFlush(p);
  log.info("LAPLACE_MARKET_ENTRY_EXECUTED strategy={} symbol={} side={} orderType=MARKET executionPriceType={} executionPrice={} notional={} leverage={}",STRATEGY,signal.symbol(),side,quote.executionPriceType(),price,notional,leverage);
  Map<String,Object> payload=base(signal,"ENTRY",p,UUID.randomUUID().toString(),reversalId);payload.put("side",side);payload.put("rawEntrySignal",signal.entrySignal());payload.put("rawStrongReversalSignal",signal.strongReversalSignal());payload.put("effectiveExecutionSide",side);payload.put("signalInverted",true);payload.put("initialCapitalUsdt",properties.getLaplace().getInitialCapitalUsdt());payload.put("positionBefore",positionBefore);payload.put("positionAfter",side);payload.put("entryReason",reversalId==null?"CONFIRMED_LAPLACE_"+side:"CONFIRMED_LAPLACE_REVERSAL");payload.put("signalDetectedAt",requested);payload.put("executionRequestedAt",requested);payload.put("executionTime",now);payload.put("orderType","MARKET");payload.put("executionAction",action);payload.put("priceSource",quote.source());payload.put("bestBid",quote.bestBid());payload.put("bestAsk",quote.bestAsk());payload.put("executionPriceType",quote.executionPriceType());payload.put("executionPrice",price);payload.put("margin",margin);payload.put("leverage",leverage);payload.put("notional",notional);payload.put("quantity",quantity);payload.put("takerFeeRate",feeRate);payload.put("entryFeeRate",feeRate);payload.put("entryFee",fee);payload.put("status",p.getStatus());saveEvent(payload,"ENTRY",reversalId,p);return p;
 }
 @Transactional public ReversalOutcome reverse(LaplaceSignalResult signal,LaplacePaperPositionEntity expected,PositionSide target,boolean openTarget){
  LaplacePaperPositionEntity p=singleOpenForUpdate(signal.symbol());if(!p.getId().equals(expected.getId()))throw new IllegalStateException("POSITION_STATE_CONFLICT");String exitSignalId=reversalKey(signal,target);if(p.getExitSignalId()!=null)throw new IllegalStateException("DUPLICATE_EXECUTION_BLOCKED");String reversalId=UUID.randomUUID().toString();Instant requested=Instant.now();MarketExecutionAction action=p.getSide()==PositionSide.LONG?MarketExecutionAction.LONG_CLOSE:MarketExecutionAction.SHORT_CLOSE;var quote=prices.quote(signal.symbol(),action);Instant now=Instant.now();BigDecimal exitNotional=p.getQuantity().multiply(quote.value()).setScale(SCALE,RoundingMode.HALF_UP);BigDecimal exitFee=exitNotional.multiply(p.getEntryFeeRate()).setScale(SCALE,RoundingMode.HALF_UP);var result=pnl.calculate(p.getSide(),p.getEntryExecutionPrice(),quote.value(),p.getQuantity(),p.getNotional(),p.getEntryFee(),exitFee);
  if(p.getLeverage()!=10||p.getNotional().compareTo(new BigDecimal("50"))!=0)log.warn("LAPLACE_LEGACY_POSITION_SIZING_PRESERVED symbol={} positionId={} notional={} leverage={}",p.getSymbol(),p.getId(),p.getNotional(),p.getLeverage());
  p.setStatus(LaplacePositionStatus.CLOSED);p.setExitSignalId(exitSignalId);p.setExitTime(now);p.setExitExecutionPrice(quote.value());p.setExitFee(exitFee);p.setGrossPnl(result.gross());p.setGrossPnlPct(result.grossPct());p.setNetPnl(result.net());p.setNetPnlPct(result.netPct());p.setHoldingMinutes(Duration.between(p.getEntryTime(),now).toMinutes());p.setExitReason(openTarget?"OPPOSITE_CONFIRMED_LAPLACE_SIGNAL":"OPPOSITE_SIGNAL_OUTSIDE_ENTRY_UNIVERSE");positions.saveAndFlush(p);
  log.info("LAPLACE_MARKET_EXIT_EXECUTED strategy={} symbol={} side={} orderType=MARKET executionPriceType={} executionPrice={} entryNotional={} leverage={}",STRATEGY,signal.symbol(),p.getSide(),quote.executionPriceType(),quote.value(),p.getNotional(),p.getLeverage());
  Map<String,Object> payload=base(signal,"EXIT",p,UUID.randomUUID().toString(),reversalId);payload.put("side",p.getSide());payload.put("closedSide",p.getSide());payload.put("incomingSignal",target);payload.put("positionBefore",p.getSide());payload.put("positionAfter","FLAT");payload.put("exitReason",p.getExitReason());payload.put("entryTime",p.getEntryTime());payload.put("entrySignalClosePrice",p.getEntrySignalClosePrice());payload.put("entryExecutionPrice",p.getEntryExecutionPrice());payload.put("exitExecutionRequestedAt",requested);payload.put("exitTime",now);payload.put("orderType","MARKET");payload.put("executionAction",action);payload.put("priceSource",quote.source());payload.put("bestBid",quote.bestBid());payload.put("bestAsk",quote.bestAsk());payload.put("executionPriceType",quote.executionPriceType());payload.put("exitExecutionPrice",quote.value());payload.put("entryNotional",p.getNotional());payload.put("exitNotional",exitNotional);payload.put("quantity",p.getQuantity());payload.put("notional",p.getNotional());payload.put("leverage",p.getLeverage());payload.put("grossPnl",p.getGrossPnl());payload.put("grossPnlPct",p.getGrossPnlPct());payload.put("entryFee",p.getEntryFee());payload.put("takerFeeRate",p.getEntryFeeRate());payload.put("exitFeeRate",p.getEntryFeeRate());payload.put("exitFee",exitFee);payload.put("totalFee",p.getEntryFee().add(exitFee));payload.put("netPnl",p.getNetPnl());payload.put("netPnlPct",p.getNetPnlPct());payload.put("holdingMinutes",p.getHoldingMinutes());payload.put("status",p.getStatus());saveEvent(payload,"EXIT",reversalId,p);
  LaplacePaperPositionEntity opened=null;if(openTarget)try{opened=open(signal,target,reversalId,p.getSide().name());}catch(RuntimeException failure){throw new IllegalStateException("REVERSAL_OPEN_FAILED",failure);}return new ReversalOutcome(p,opened,reversalId);
 }
 @Transactional public boolean closeAtStopLoss(String positionId, com.crypto.domain.model.Kline candle){
  LaplacePaperPositionEntity p=positions.findByIdForUpdate(positionId).orElse(null);if(p==null||!STRATEGY.equals(p.getStrategy())||p.getStatus()!=LaplacePositionStatus.OPEN)return false;
  BigDecimal multiplier=p.getSide()==PositionSide.LONG?BigDecimal.ONE.subtract(properties.getLaplace().getStopLossPct()):BigDecimal.ONE.add(properties.getLaplace().getStopLossPct());BigDecimal stopPrice=p.getEntryExecutionPrice().multiply(multiplier).setScale(SCALE,RoundingMode.HALF_UP);
  boolean hit=p.getSide()==PositionSide.LONG?candle.getLow().compareTo(stopPrice)<=0:candle.getHigh().compareTo(stopPrice)>=0;if(!hit)return false;
  String exitSignalId=STRATEGY+":"+p.getSymbol()+":"+candle.getCloseTime()+":STOP_LOSS";BigDecimal exitNotional=p.getQuantity().multiply(stopPrice).setScale(SCALE,RoundingMode.HALF_UP);BigDecimal exitFee=exitNotional.multiply(p.getEntryFeeRate()).setScale(SCALE,RoundingMode.HALF_UP);var result=pnl.calculate(p.getSide(),p.getEntryExecutionPrice(),stopPrice,p.getQuantity(),p.getNotional(),p.getEntryFee(),exitFee);Instant now=Instant.now();
  p.setStatus(LaplacePositionStatus.CLOSED);p.setExitSignalId(exitSignalId);p.setExitTime(now);p.setExitExecutionPrice(stopPrice);p.setExitFee(exitFee);p.setGrossPnl(result.gross());p.setGrossPnlPct(result.grossPct());p.setNetPnl(result.net());p.setNetPnlPct(result.netPct());p.setHoldingMinutes(Duration.between(p.getEntryTime(),now).toMinutes());p.setExitReason("STOP_LOSS");positions.saveAndFlush(p);
  Map<String,Object> payload=new LinkedHashMap<>();payload.put("eventType","EXIT");payload.put("eventId",UUID.randomUUID().toString());payload.put("strategy",STRATEGY);payload.put("strategyVersion",VERSION);payload.put("positionId",p.getId());payload.put("symbol",p.getSymbol());payload.put("side",p.getSide());payload.put("closedSide",p.getSide());payload.put("positionBefore",p.getSide());payload.put("positionAfter","FLAT");payload.put("exitReason","STOP_LOSS");payload.put("stopLossPct",properties.getLaplace().getStopLossPct());payload.put("stopLossPrice",stopPrice);payload.put("stopLossCandleOpenTime",candle.getOpenTime());payload.put("stopLossCandleCloseTime",candle.getCloseTime());payload.put("stopLossCandleHigh",candle.getHigh());payload.put("stopLossCandleLow",candle.getLow());payload.put("entryTime",p.getEntryTime());payload.put("entryExecutionPrice",p.getEntryExecutionPrice());payload.put("exitTime",now);payload.put("exitExecutionPrice",stopPrice);payload.put("executionPriceType","STOP_PRICE");payload.put("entryNotional",p.getNotional());payload.put("exitNotional",exitNotional);payload.put("margin",p.getMargin());payload.put("quantity",p.getQuantity());payload.put("leverage",p.getLeverage());payload.put("entryFee",p.getEntryFee());payload.put("exitFee",exitFee);payload.put("totalFee",p.getEntryFee().add(exitFee));payload.put("grossPnl",p.getGrossPnl());payload.put("netPnl",p.getNetPnl());payload.put("status",p.getStatus());saveEvent(payload,"EXIT",null,p);log.info("LAPLACE_STOP_LOSS_EXECUTED symbol={} positionId={} side={} stopPrice={} candleCloseTime={}",p.getSymbol(),p.getId(),p.getSide(),stopPrice,candle.getCloseTime());return true;
 }
 public void drainTradeEvents(){writer.drain();}
 boolean hasAvailableBalance(BigDecimal required){return availableBalance().compareTo(required)>=0;}
 BigDecimal availableBalance(){BigDecimal realized=positions.findByStrategyAndStatus(STRATEGY,LaplacePositionStatus.CLOSED).stream().map(x->x.getNetPnl()==null?BigDecimal.ZERO:x.getNetPnl()).reduce(BigDecimal.ZERO,BigDecimal::add);List<LaplacePaperPositionEntity> open=positions.findByStrategyAndStatus(STRATEGY,LaplacePositionStatus.OPEN);BigDecimal locked=open.stream().map(LaplacePaperPositionEntity::getMargin).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal openEntryFees=open.stream().map(x->x.getEntryFee()==null?BigDecimal.ZERO:x.getEntryFee()).reduce(BigDecimal.ZERO,BigDecimal::add);return properties.getLaplace().getInitialCapitalUsdt().add(realized).subtract(locked).subtract(openEntryFees);}
 private void assertNoOpen(String symbol){if(!positions.findOpenForUpdate(STRATEGY,symbol,LaplacePositionStatus.OPEN).isEmpty())throw new IllegalStateException("POSITION_STATE_CONFLICT");}
 public LaplacePaperPositionEntity singleOpenForUpdate(String symbol){List<LaplacePaperPositionEntity>x=positions.findOpenForUpdate(STRATEGY,symbol,LaplacePositionStatus.OPEN);if(x.size()!=1)throw new IllegalStateException("POSITION_STATE_CONFLICT");return x.getFirst();}
 private void saveEvent(Map<String,Object> payload,String type,String reversal,LaplacePaperPositionEntity p){String id=(String)payload.get("eventId");writer.tryJson(payload).ifPresentOrElse(json->{events.save(LaplaceTradeEventEntity.builder().eventId(id).eventType(type).reversalId(reversal).positionId(p.getId()).symbol(p.getSymbol()).payloadJson(json).jsonlWritten(false).createdAt(Instant.now()).build());log.info("LAPLACE_TRADE_EVENT_PUBLISHED eventId={} eventType={} symbol={}",id,type,p.getSymbol());},()->log.error("LAPLACE_TRADE_EVENT_SERIALIZATION_SKIPPED eventId={} eventType={} symbol={} positionId={}",id,type,p.getSymbol(),p.getId()));}
 private Map<String,Object> base(LaplaceSignalResult s,String type,LaplacePaperPositionEntity p,String eventId,String reversal){Map<String,Object>m=new LinkedHashMap<>();m.put("eventType",type);m.put("eventId",eventId);m.put("reversalId",reversal);m.put("strategy",STRATEGY);m.put("strategyVersion",VERSION);m.put("positionId",p.getId());m.put("symbol",s.symbol());m.put("timeframe",s.timeframe());m.put("kernel",s.kernel());m.put("bandwidth",s.bandwidth());m.put("source",s.source());m.put("repaint",s.repaint());m.put("startupUniverseSessionId",universe.sessionId());m.put("startupVolumeValue",universe.startupVolume(s.symbol()));m.put("minimumVolumeThreshold",universe.minimumVolumeThreshold());m.put("inStartupEntryUniverse",universe.symbols().contains(s.symbol()));m.put("signalCandleOpenTime",s.signalCandleOpenTime());m.put("signalCandleCloseTime",s.signalCandleCloseTime());m.put("signalCandleClose",s.signalCandleClose());m.put("regressionCurrent",s.regressionCurrent());m.put("regressionPrevious",s.regressionPrevious());m.put("regressionTwoBarsAgo",s.regressionTwoBarsAgo());m.put("currentSlope",s.currentSlope());m.put("previousSlope",s.previousSlope());m.put("currentAtr14",s.currentAtr14());m.put("previousAtr14",s.previousAtr14());m.put("currentNormalizedSlope",s.currentNormalizedSlope());m.put("previousNormalizedSlope",s.previousNormalizedSlope());m.put("entryThreshold",s.entryThreshold());m.put("reversalThreshold",s.reversalThreshold());m.put("confirmationBars",s.confirmationBars());m.put("entrySignal",s.entrySignal());m.put("strongReversalSignal",s.strongReversalSignal());m.put("rawEntrySignal",s.entrySignal());m.put("rawStrongReversalSignal",s.strongReversalSignal());m.put("signalInverted",true);return m;}
 public static String entryKey(LaplaceSignalResult s,PositionSide side){return STRATEGY+":"+s.symbol()+":"+s.signalCandleCloseTime()+":ENTRY:"+side;}public static String reversalKey(LaplaceSignalResult s,PositionSide side){return STRATEGY+":"+s.symbol()+":"+s.signalCandleCloseTime()+":REVERSAL:"+side;}
 public record ReversalOutcome(LaplacePaperPositionEntity closed,LaplacePaperPositionEntity opened,String reversalId){}
}
