package com.crypto.laplace.execution;

import com.crypto.common.enums.PositionSide;
import com.crypto.laplace.config.LaplaceStrategyProperties;
import com.crypto.laplace.model.*;
import com.crypto.laplace.persistence.*;
import com.crypto.laplace.pool.*;
import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicBoolean;import java.util.concurrent.locks.ReentrantLock;
import lombok.extern.slf4j.Slf4j;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.stereotype.Service;

/** Keeps raw strategy signals untouched and applies the contrarian mapping only at execution. */
@Slf4j @Service
public class LaplacePaperTradeCoordinator {
 private final LaplaceStrategyProperties config;private final LaplacePaperPositionRepository positions;private final LaplacePaperExecutionService execution;private final LaplaceTradeJsonlWriter writer;private final ConcurrentHashMap<String,ReentrantLock> locks=new ConcurrentHashMap<>();private final ConcurrentHashMap<String,LaplaceSignal> rawStates=new ConcurrentHashMap<>();private final Set<String> initializedSymbols=ConcurrentHashMap.newKeySet();private final LaplaceCoinPoolService coinPool;private final LaplaceEntryDecisionService entryDecisionService;private final LaplaceVolumeProfileService volumeProfileService;private final Kural3WarmupService warmupService;
 @Autowired
 public LaplacePaperTradeCoordinator(LaplaceStrategyProperties config,LaplacePaperPositionRepository positions,LaplacePaperExecutionService execution,LaplaceTradeJsonlWriter writer,LaplaceCoinPoolService coinPool,LaplaceEntryDecisionService entryDecisionService,LaplaceVolumeProfileService volumeProfileService,Kural3WarmupService warmupService){this.config=config;this.positions=positions;this.execution=execution;this.writer=writer;this.coinPool=coinPool;this.entryDecisionService=entryDecisionService;this.volumeProfileService=volumeProfileService;this.warmupService=warmupService;}
 public LaplacePaperTradeCoordinator(LaplaceStrategyProperties config,LaplacePaperPositionRepository positions,LaplacePaperExecutionService execution,LaplaceTradeJsonlWriter writer,LaplaceCoinPoolService coinPool,LaplaceEntryDecisionService entryDecisionService,LaplaceVolumeProfileService volumeProfileService){this(config,positions,execution,writer,coinPool,entryDecisionService,volumeProfileService,null);}
 public LaplacePaperTradeCoordinator(LaplaceStrategyProperties config,LaplacePaperPositionRepository positions,LaplacePaperExecutionService execution,LaplaceTradeJsonlWriter writer,LaplaceCoinPoolService coinPool,LaplaceEntryDecisionService entryDecisionService){this(config,positions,execution,writer,coinPool,entryDecisionService,null,null);}
 public LaplacePaperTradeCoordinator(LaplaceStrategyProperties config,LaplacePaperPositionRepository positions,LaplacePaperExecutionService execution,LaplaceTradeJsonlWriter writer,LaplaceCoinPoolService coinPool){this(config,positions,execution,writer,coinPool,new LaplaceEntryDecisionService(new LaplaceRiskyEntryFilter()),null,null);}
 public LaplacePaperTradeCoordinator(LaplaceStrategyProperties config,LaplacePaperPositionRepository positions,LaplacePaperExecutionService execution,LaplaceTradeJsonlWriter writer){this(config,positions,execution,writer,null,new LaplaceEntryDecisionService(new LaplaceRiskyEntryFilter()),null,null);}
private final AtomicBoolean paperDisabledLogged=new AtomicBoolean(false);
 private final ConcurrentHashMap<String,Instant> stopCooldowns=new ConcurrentHashMap<>();
 private final ConcurrentHashMap<String,LaplaceSignal> oppositeSignalLocks=new ConcurrentHashMap<>();
 private final ConcurrentHashMap<String,LaplaceSignal> riskBlockedDirections=new ConcurrentHashMap<>();
 private volatile Instant cycleStartedAt=Instant.EPOCH; private final CycleMetrics metrics=new CycleMetrics();
 public void beginCycle(Instant startedAt){cycleStartedAt=startedAt;metrics.reset();execution.beginPricingCycle();}
 public CycleSummary cycleSummary(){return metrics.snapshot(execution.pricingMetrics());}
 public Set<String> managementSymbols(){Set<String>x=new HashSet<>();for(var p:positions.findByStrategyAndStatus(LaplacePaperExecutionService.STRATEGY,LaplacePositionStatus.OPEN))x.add(p.getSymbol());return Set.copyOf(x);}
 public PositionSide mapRawSignalToExecutionSide(LaplaceSignal raw){return switch(raw){case LONG->PositionSide.SHORT;case SHORT->PositionSide.LONG;case NONE->null;};}
 /** Startup history establishes a raw baseline only; it deliberately never executes. */
 public void initializeBaseline(String symbol,LaplaceSignal raw){initializedSymbols.add(symbol);if(raw==LaplaceSignal.NONE)rawStates.remove(symbol);else rawStates.put(symbol,raw);if(coinPool!=null)coinPool.baseline(symbol, trend(raw));log.info("LAPLACE_STARTUP_RAW_BASELINE_INITIALIZED symbol={} startupRawSignalState={}",symbol,raw);}
 public void onStopLossClosed(String symbol,String entryRawSignal,String positionSide,String positionId,Instant stoppedAt){
  if(symbol==null||entryRawSignal==null)return;
  if(coinPool!=null)coinPool.recordStop(symbol,entryRawSignal,positionSide,positionId,stoppedAt);
  if(config.getLaplace().getStopReentryPolicy()==StopReentryPolicy.REQUIRE_OPPOSITE_SIGNAL)oppositeSignalLocks.put(symbol,LaplaceSignal.valueOf(entryRawSignal));
  if(config.getLaplace().getStopReentryPolicy()==StopReentryPolicy.ALLOW){rawStates.remove(symbol);return;}
  try{LaplaceSignal stoppedSignal=LaplaceSignal.valueOf(entryRawSignal);rawStates.putIfAbsent(symbol,stoppedSignal);if(config.getLaplace().getStopReentryPolicy()==StopReentryPolicy.COOLDOWN)stopCooldowns.put(symbol,Instant.now().plusSeconds(config.getLaplace().getStopReentryCooldownMinutes()*60));log.info("LAPLACE_STOP_REENTRY_LOCKED symbol={} rawSignal={} policy={} entryBlockedReason=WAITING_FOR_NEW_SIGNAL",symbol,rawStates.get(symbol),config.getLaplace().getStopReentryPolicy());}
  catch(IllegalArgumentException invalid){log.warn("LAPLACE_STOP_REENTRY_LOCK_SKIPPED symbol={} invalidRawSignal={}",symbol,entryRawSignal);}
 }
 public void onSignal(LaplaceSignalResult signal,boolean entryUniverseSnapshotContainsSymbol){
  if(signal==null||signal.startupState()!=StartupState.ACTIVE||signal.postStartupClosedBarCount()<1)return;
  if(!config.getLaplace().isPaperExecutionEnabled()){if(signal.entrySignal()!=LaplaceSignal.NONE&&paperDisabledLogged.compareAndSet(false,true))log.warn("LAPLACE_PAPER_EXECUTION_DISABLED strategy={} symbol={}",LaplacePaperExecutionService.STRATEGY,signal.symbol());return;}
  ReentrantLock lock=locks.computeIfAbsent(signal.symbol(),s->new ReentrantLock());lock.lock();try {
   // The iteration snapshot is deliberately not authoritative: observeTrend may activate this symbol now.
   boolean poolActive=coinPool==null || coinPool.observeTrend(signal.symbol(),trend(signal.entrySignal()));
   if(!entryUniverseSnapshotContainsSymbol&&poolActive)metrics.activated.incrementAndGet();else if(!poolActive)metrics.waiting.incrementAndGet();
   if(signal.entrySignal()==LaplaceSignal.NONE){log.info("LAPLACE_NONE_SIGNAL_IGNORED symbol={} blockedRawDirectionPreserved=true",signal.symbol());return;}
   boolean oppositeAllowed=oppositeSignalAllowed(signal.symbol(),signal.entrySignal());
   if(config.getLaplace().getStopReentryPolicy()==StopReentryPolicy.COOLDOWN&&stopCooldowns.getOrDefault(signal.symbol(),Instant.EPOCH).isBefore(Instant.now())){rawStates.remove(signal.symbol());stopCooldowns.remove(signal.symbol());}
   LaplaceSignal previous=rawStates.put(signal.symbol(),signal.entrySignal());if(previous==null&&!initializedSymbols.contains(signal.symbol())){initializedSymbols.add(signal.symbol());log.info("LAPLACE_STARTUP_RAW_BASELINE_INITIALIZED symbol={} startupRawSignalState={}",signal.symbol(),signal.entrySignal());return;}
   boolean fresh=previous==null||previous!=signal.entrySignal();if(fresh)metrics.fresh.incrementAndGet();LaplaceEntryDecision evaluation=entryDecisionService.decide(signal);PositionSide effective=evaluation.effectiveExecutionSide();
   boolean riskyDirectionBlocked=isRiskyDirectionBlocked(signal.symbol(),signal.entrySignal());
   if(fresh&&!riskyDirectionBlocked&&hasRiskyDirectionBlock(signal.symbol()))clearRiskyDirectionBlock(signal.symbol());
   logDecision(signal,effective,evaluation,fresh?"EVALUATE":"NOT_FRESH",false);
   if(fresh&&!oppositeAllowed)metrics.blockedByReentry.incrementAndGet();
   if(riskyDirectionBlocked){log.info("LAPLACE_ENTRY_DECISION decision=SKIP entryAllowed=false reason=RAW_DIRECTION_ALREADY_BLOCKED entryStateConsumed=true symbol={} rawSignal={} signalCandleCloseTime={}",signal.symbol(),signal.entrySignal(),signal.signalCandleCloseTime());return;}
   if(fresh&&oppositeAllowed)coordinate(signal,poolActive,effective,entryUniverseSnapshotContainsSymbol,Instant.now(),previous);
  }finally{lock.unlock();}
 }
 private boolean oppositeSignalAllowed(String symbol,LaplaceSignal current){if(config.getLaplace().getStopReentryPolicy()!=StopReentryPolicy.REQUIRE_OPPOSITE_SIGNAL)return true;if(coinPool!=null)return coinPool.allowAfterOppositeSignal(symbol,current.name());LaplaceSignal stopped=oppositeSignalLocks.get(symbol);if(stopped==null)return true;if(current==LaplaceSignal.NONE||current==stopped)return false;oppositeSignalLocks.remove(symbol);return true;}
 private LaplaceTrend trend(LaplaceSignal s){return s==LaplaceSignal.LONG?LaplaceTrend.LONG:s==LaplaceSignal.SHORT?LaplaceTrend.SHORT:LaplaceTrend.NEUTRAL;}
 private String current(String symbol){var x=positions.findByStrategyAndSymbolAndStatus(LaplacePaperExecutionService.STRATEGY,symbol,LaplacePositionStatus.OPEN);return x.isEmpty()?"FLAT":x.get(0).getSide().name();}
 private void coordinate(LaplaceSignalResult signal,boolean poolActiveAfterTransition,PositionSide effective,boolean entryUniverseSnapshotContainsSymbol,Instant eligibilityEvaluatedAt,LaplaceSignal previousRawState){
  List<LaplacePaperPositionEntity> open=positions.findByStrategyAndSymbolAndStatus(LaplacePaperExecutionService.STRATEGY,signal.symbol(),LaplacePositionStatus.OPEN);if(open.size()>1){failure(signal,"CONFLICT","NONE","POSITION_STATE_CONFLICT",null,false);return;}
  LaplaceCoinPoolService.EntryEligibility eligibility=coinPool==null?null:coinPool.isCurrentlyEligibleForEntry(signal.symbol());
  boolean currentlyEligible=coinPool==null?poolActiveAfterTransition:eligibility.allowed();
  if(open.isEmpty()){if(effective==null||!signal.eligibleForExecution())return;if(!currentlyEligible){
    Map<String,Object> audit=eligibilityAudit(eligibility,entryUniverseSnapshotContainsSymbol,"FLAT",eligibilityEvaluatedAt);
    String failureReason=eligibility!=null&&eligibility.blockReason()!=null?eligibility.blockReason():"SYMBOL_OUTSIDE_ENTRY_UNIVERSE";
    if("SYMBOL_OUTSIDE_ENTRY_UNIVERSE".equals(failureReason)){metrics.outsideUniverse.incrementAndGet();if(eligibility!=null&&eligibility.poolState()==LaplaceCoinPoolState.ACTIVE&&signal.eligibleForExecution())log.error("LAPLACE_STALE_ENTRY_UNIVERSE_INCONSISTENCY symbol={} poolState=ACTIVE eligibleForExecution=true currentPosition=FLAT freshSignal=true snapshotContains={}",signal.symbol(),entryUniverseSnapshotContainsSymbol);}
    metrics.failures.incrementAndGet();failure(signal,"FLAT","ENTRY",failureReason,null,false,audit);return;
   }LaplaceEntryDecision decision=entryDecisionService.decide(signal);if(!decision.entryAllowed()){blockRiskyDirection(signal);writer.entrySkipped(signal,effective,decision);logDecision(signal,effective,decision,"SKIP",true);return;}Kural3WarmupStatus warmup=warmupService==null?Kural3WarmupStatus.READY:warmupService.status(signal.symbol());if(warmup!=Kural3WarmupStatus.READY){if(warmup==Kural3WarmupStatus.FAILED)warmupService.retryFailed(signal.symbol());restoreRawState(signal.symbol(),previousRawState);log.info("LAPLACE_VOLUME_PROFILE_ENTRY_SKIPPED symbol={} rawSignal={} reason=VP_WARMUP_{} rawSignalConsumed=false persistentDirectionBlock=false",signal.symbol(),signal.entrySignal(),warmup);return;}LaplaceVolumeProfileDecision vp=volumeProfileService==null?null:volumeProfileService.evaluate(signal.symbol(),signal.signalCandleCloseTime(),signal.signalCandleClose(),effective);if(vp!=null){logVolumeProfile(signal,effective,decision,vp);if(!vp.volumeProfileAllowed()){restoreRawState(signal.symbol(),previousRawState);log.info("LAPLACE_VOLUME_PROFILE_ENTRY_SKIPPED symbol={} rawSignal={} reason={} rawSignalConsumed=false persistentDirectionBlock=false",signal.symbol(),signal.entrySignal(),vp.rejectionReason());return;}}logDecision(signal,effective,decision,"OPEN",false);metrics.entryAttempts.incrementAndGet();Instant requestStartedAt=Instant.now();try{execution.open(signal,effective,null,"FLAT");metrics.entryOpened.incrementAndGet();writer.drain();}catch(RuntimeException e){metrics.failures.incrementAndGet();String reason=reason(e,"ENTRY_EXECUTION_FAILED");if("BOOK_TICKER_UNAVAILABLE".equals(reason)){Map<String,Object>a=new LinkedHashMap<>();a.put("requestedSide",effective);a.put("requestedExecutionPriceType",effective==PositionSide.LONG?"ASK":"BID");a.put("requestStartedAt",requestStartedAt);a.put("failedAt",Instant.now());failure(signal,"FLAT","ENTRY",reason,e,false,a);}else failure(signal,"FLAT","ENTRY",reason,e,true);}return;}
  metrics.alreadyOpen.incrementAndGet();
  LaplacePaperPositionEntity p=open.get(0);if(effective==null||p.getSide()==effective){log.info("LAPLACE_SAME_EFFECTIVE_SIDE_SIGNAL_IGNORED symbol={} side={}",signal.symbol(),p.getSide());return;}
  PositionSide reversalTarget=effective;if(signal.strongReversalSignal()==LaplaceSignal.NONE||reversalTarget==null)return;
  LaplaceEntryDecision decision=entryDecisionService.decide(signal);if(!decision.entryAllowed()){blockRiskyDirection(signal);writer.entrySkipped(signal,effective,decision);logDecision(signal,effective,decision,"SKIP",true);}
  boolean reversalTargetAllowed=(eligibility==null?poolActiveAfterTransition:eligibility.poolState()==LaplaceCoinPoolState.ACTIVE&&!eligibility.reentryBlocked())&&decision.entryAllowed();
  try{execution.reverse(signal,p,effective,reversalTargetAllowed);writer.drain();}catch(RuntimeException e){failure(signal,p.getSide().name(),"REVERSAL",reason(e,"REVERSAL_CLOSE_FAILED"),e,true);}
 }
 private void logDecision(LaplaceSignalResult s,PositionSide effective,LaplaceEntryDecision d,String decision,boolean consumed){log.info("LAPLACE_ENTRY_DECISION symbol={} rawSignal={} rawLongRule={} rawShortRule={} signalInverted={} effectiveExecutionSide={} previousRawTakerImbalance={} ret120mPct={} previous30mRawReturnPct={} aligned120mReturnPct={} atrPercentage={} currentNormalizedSlope={} previousNormalizedSlope={} riskyEntry={} strongSlope={} entryAllowed={} rejectionReason={} decision={} blockedRawDirection={} entryStateConsumed={}",s.symbol(),s.entrySignal(),d.rawLongRule(),d.rawShortRule(),d.signalInverted(),effective,s.previousRawTakerImbalance(),s.ret120mPct(),s.previous30mRawReturnPct(),s.aligned120mReturnPct(),s.atrPercentage(),s.currentNormalizedSlope(),s.previousNormalizedSlope(),d.riskyEntry(),d.strongConfirmedSignal(),d.entryAllowed(),d.skipReasons(),decision,consumed?s.entrySignal():null,consumed);}
 private void logVolumeProfile(LaplaceSignalResult s,PositionSide side,LaplaceEntryDecision existing,LaplaceVolumeProfileDecision v){log.info("LAPLACE_KURAL3 symbol={} signalTime={} rawSignal={} signalInverted={} effectiveExecutionSide={} existingEntryAllowed={} previousNySessionDate={} previousNySessionStart={} previousNySessionEnd={} previousSessionLow={} previousSessionHigh={} previousSessionPoc={} volumeProfileRows={} entryPrice={} entryInsidePreviousSessionRange={} localDeltaRatio={} currentDelta60m={} insideProfileLongAllowed={} insideProfileShortAllowed={} outsideProfileLongAllowed={} outsideProfileShortAllowed={} volumeProfileAllowed={} finalEntryAllowed={} volumeProfileRejectionReason={}",s.symbol(),s.signalCandleCloseTime(),s.entrySignal(),existing.signalInverted(),side,existing.entryAllowed(),v.previousNySessionDate(),v.previousNySessionStart(),v.previousNySessionEnd(),v.previousSessionLow(),v.previousSessionHigh(),v.previousSessionPoc(),v.volumeProfileRows(),v.entryPrice(),v.entryInsidePreviousSessionRange(),v.localDeltaRatio(),v.currentDelta60m(),v.insideProfileLongAllowed(),v.insideProfileShortAllowed(),v.outsideProfileLongAllowed(),v.outsideProfileShortAllowed(),v.volumeProfileAllowed(),existing.entryAllowed()&&v.volumeProfileAllowed(),v.rejectionReason());}
 private void restoreRawState(String symbol,LaplaceSignal previous){if(previous==null)rawStates.remove(symbol);else rawStates.put(symbol,previous);}
 private void failure(LaplaceSignalResult s,String current,String action,String reason,Throwable e,boolean retry){writer.failure(s.symbol(),s.signalCandleCloseTime(),current,action,reason,e,retry);writer.drain();}
 private boolean isRiskyDirectionBlocked(String symbol,LaplaceSignal raw){return riskBlockedDirections.get(symbol)==raw||(coinPool!=null&&coinPool.isRiskyDirectionBlocked(symbol,raw.name()));}
 private boolean hasRiskyDirectionBlock(String symbol){return riskBlockedDirections.containsKey(symbol)||(coinPool!=null&&coinPool.hasRiskyDirectionBlock(symbol));}
 private void blockRiskyDirection(LaplaceSignalResult signal){riskBlockedDirections.put(signal.symbol(),signal.entrySignal());if(coinPool!=null)coinPool.blockRiskyDirection(signal.symbol(),signal.entrySignal().name(),signal.signalCandleCloseTime());}
 private void clearRiskyDirectionBlock(String symbol){riskBlockedDirections.remove(symbol);if(coinPool!=null)coinPool.clearRiskyDirectionBlock(symbol);}
 private void failure(LaplaceSignalResult s,String current,String action,String reason,Throwable e,boolean retry,Map<String,Object> audit){writer.failure(s.symbol(),s.signalCandleCloseTime(),current,action,reason,e,retry,audit);writer.drain();}
 private Map<String,Object> eligibilityAudit(LaplaceCoinPoolService.EntryEligibility e,boolean snapshot,String position,Instant evaluatedAt){Map<String,Object>x=new LinkedHashMap<>();x.put("poolStateAtEvaluation",e==null?null:e.poolState());x.put("includedInPoolAtEvaluation",e!=null&&e.includedInPool());x.put("newEntryAllowed",e!=null&&e.allowed());x.put("entryUniverseSnapshotContainsSymbol",snapshot);x.put("reentryBlocked",e!=null&&e.reentryBlocked());x.put("positionState",position);x.put("eligibilityEvaluatedAt",evaluatedAt);x.put("cycleStartedAt",cycleStartedAt);x.put("poolStateUpdatedAt",e==null?null:e.poolStateUpdatedAt());return x;}
 public record CycleSummary(int waitingSymbols,int activatedSymbols,int freshSignalCount,int entryAttemptCount,int entryOpenedCount,int outsideEntryUniverseCount,int blockedByReentryCount,int alreadyOpenCount,int failureCount,int bookTickerRequestCount,int bookTickerFailureCount,int bulkBookTickerRequestCount){}
 private static final class CycleMetrics{final java.util.concurrent.atomic.AtomicInteger waiting=new java.util.concurrent.atomic.AtomicInteger(),activated=new java.util.concurrent.atomic.AtomicInteger(),fresh=new java.util.concurrent.atomic.AtomicInteger(),entryAttempts=new java.util.concurrent.atomic.AtomicInteger(),entryOpened=new java.util.concurrent.atomic.AtomicInteger(),outsideUniverse=new java.util.concurrent.atomic.AtomicInteger(),blockedByReentry=new java.util.concurrent.atomic.AtomicInteger(),alreadyOpen=new java.util.concurrent.atomic.AtomicInteger(),failures=new java.util.concurrent.atomic.AtomicInteger();void reset(){waiting.set(0);activated.set(0);fresh.set(0);entryAttempts.set(0);entryOpened.set(0);outsideUniverse.set(0);blockedByReentry.set(0);alreadyOpen.set(0);failures.set(0);}CycleSummary snapshot(LaplaceExecutionPriceProvider.RequestMetrics p){if(p==null)p=new LaplaceExecutionPriceProvider.RequestMetrics(0,0,0);return new CycleSummary(waiting.get(),activated.get(),fresh.get(),entryAttempts.get(),entryOpened.get(),outsideUniverse.get(),blockedByReentry.get(),alreadyOpen.get(),failures.get(),p.bookTickerRequestCount(),p.bookTickerFailureCount(),p.bulkBookTickerRequestCount());}}
 private String reason(RuntimeException e,String fallback){return e.getMessage()!=null&&Set.of("BOOK_TICKER_UNAVAILABLE","EXECUTION_PRICE_UNAVAILABLE","INVALID_QUANTITY","INVALID_NOTIONAL","POSITION_STATE_CONFLICT","DUPLICATE_EXECUTION_BLOCKED","REVERSAL_OPEN_FAILED").contains(e.getMessage())?e.getMessage():fallback;}
}
