package com.crypto.laplace.execution;

import com.crypto.common.enums.PositionSide;import com.crypto.laplace.config.LaplaceStrategyProperties;import com.crypto.laplace.model.*;import com.crypto.laplace.persistence.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.locks.ReentrantLock;import lombok.RequiredArgsConstructor;import lombok.extern.slf4j.Slf4j;import org.springframework.stereotype.Service;
@Slf4j @Service @RequiredArgsConstructor
public class LaplacePaperTradeCoordinator {
 private final LaplaceStrategyProperties config;private final LaplacePaperPositionRepository positions;private final LaplacePaperExecutionService execution;private final LaplaceTradeJsonlWriter writer;private final ConcurrentHashMap<String,ReentrantLock> locks=new ConcurrentHashMap<>();
 public Set<String> managementSymbols(){Set<String>x=new HashSet<>();for(var p:positions.findByStrategyAndStatus(LaplacePaperExecutionService.STRATEGY,LaplacePositionStatus.OPEN))x.add(p.getSymbol());return Set.copyOf(x);}
 public void onSignal(LaplaceSignalResult signal,boolean inEntryUniverse){
  if(signal==null||signal.startupState()!=StartupState.ACTIVE||signal.postStartupClosedBarCount()<1)return;
  if(!config.getLaplace().isPaperExecutionEnabled()){if(signal.entrySignal()!=LaplaceSignal.NONE)writer.failure(signal.symbol(),signal.signalCandleCloseTime(),"UNKNOWN","ENTRY","PAPER_EXECUTION_DISABLED",null,false);return;}
  ReentrantLock lock=locks.computeIfAbsent(signal.symbol(),s->new ReentrantLock());lock.lock();try{coordinate(signal,inEntryUniverse);}finally{lock.unlock();}
 }
 private void coordinate(LaplaceSignalResult signal,boolean inEntryUniverse){
  List<LaplacePaperPositionEntity> open=positions.findByStrategyAndSymbolAndStatus(LaplacePaperExecutionService.STRATEGY,signal.symbol(),LaplacePositionStatus.OPEN);if(open.size()>1){failure(signal,"CONFLICT","NONE","POSITION_STATE_CONFLICT",null,false);log.error("LAPLACE_POSITION_STATE_CONFLICT strategy={} symbol={}",LaplacePaperExecutionService.STRATEGY,signal.symbol());return;}
  if(open.isEmpty()){if(signal.entrySignal()==LaplaceSignal.NONE)return;if(!signal.eligibleForExecution())return;if(!inEntryUniverse){failure(signal,"FLAT","ENTRY","SYMBOL_OUTSIDE_ENTRY_UNIVERSE",null,false);return;}PositionSide side=side(signal.entrySignal());try{log.info("LAPLACE_ENTRY_REQUESTED strategy={} symbol={} side={} signalCandleCloseTime={}",LaplacePaperExecutionService.STRATEGY,signal.symbol(),side,signal.signalCandleCloseTime());var p=execution.open(signal,side,null,"FLAT");writer.drain();log.info("LAPLACE_ENTRY_COMPLETED strategy={} symbol={} side={} positionId={} executionPrice={}",LaplacePaperExecutionService.STRATEGY,p.getSymbol(),p.getSide(),p.getId(),p.getEntryExecutionPrice());}catch(RuntimeException e){failure(signal,"FLAT","ENTRY",reason(e,"ENTRY_EXECUTION_FAILED"),e,true);log.error("LAPLACE_ENTRY_FAILED strategy={} symbol={} side={} failureReason={}",LaplacePaperExecutionService.STRATEGY,signal.symbol(),side,e.getMessage());}return;}
  LaplacePaperPositionEntity current=open.getFirst();if(signal.entrySignal()!=LaplaceSignal.NONE&&current.getSide()==side(signal.entrySignal())){log.debug("LAPLACE_SAME_SIDE_SIGNAL_IGNORED strategy={} symbol={} side={} positionId={}",LaplacePaperExecutionService.STRATEGY,signal.symbol(),current.getSide(),current.getId());return;}
  PositionSide target=current.getSide()==PositionSide.LONG?PositionSide.SHORT:PositionSide.LONG;if(signal.strongReversalSignal()==LaplaceSignal.NONE||side(signal.strongReversalSignal())!=target)return;
  try{log.info("LAPLACE_REVERSAL_REQUESTED strategy={} symbol={} side={} positionId={} signalCandleCloseTime={}",LaplacePaperExecutionService.STRATEGY,signal.symbol(),target,current.getId(),signal.signalCandleCloseTime());var out=execution.reverse(signal,current,target,inEntryUniverse);writer.drain();log.info("LAPLACE_POSITION_CLOSED strategy={} symbol={} side={} positionId={} reversalId={} executionPrice={}",LaplacePaperExecutionService.STRATEGY,signal.symbol(),current.getSide(),current.getId(),out.reversalId(),out.closed().getExitExecutionPrice());if(out.opened()!=null)log.info("LAPLACE_REVERSAL_ENTRY_COMPLETED strategy={} symbol={} side={} positionId={} reversalId={} executionPrice={}",LaplacePaperExecutionService.STRATEGY,signal.symbol(),target,out.opened().getId(),out.reversalId(),out.opened().getEntryExecutionPrice());}catch(RuntimeException e){failure(signal,current.getSide().name(),"REVERSAL",reason(e,"REVERSAL_CLOSE_FAILED"),e,true);log.error("LAPLACE_REVERSAL_FAILED strategy={} symbol={} positionId={} failureReason={}",LaplacePaperExecutionService.STRATEGY,signal.symbol(),current.getId(),e.getMessage());}
 }
 private void failure(LaplaceSignalResult s,String current,String action,String reason,Throwable e,boolean retry){writer.failure(s.symbol(),s.signalCandleCloseTime(),current,action,reason,e,retry);writer.drain();}
 private String reason(RuntimeException e,String fallback){return e.getMessage()!=null&&Set.of("EXECUTION_PRICE_UNAVAILABLE","INVALID_QUANTITY","INVALID_NOTIONAL","POSITION_STATE_CONFLICT","DUPLICATE_EXECUTION_BLOCKED","REVERSAL_OPEN_FAILED").contains(e.getMessage())?e.getMessage():fallback;}
 private PositionSide side(LaplaceSignal signal){return signal==LaplaceSignal.LONG?PositionSide.LONG:PositionSide.SHORT;}
}
