package com.crypto.laplace.execution;
import com.crypto.laplace.config.LaplaceStrategyProperties;import com.crypto.laplace.persistence.*;import com.fasterxml.jackson.databind.ObjectMapper;import java.nio.file.*;import java.time.Instant;import java.util.*;import lombok.RequiredArgsConstructor;import lombok.extern.slf4j.Slf4j;import org.springframework.boot.ApplicationArguments;import org.springframework.boot.ApplicationRunner;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Slf4j @Service @RequiredArgsConstructor
public class LaplaceTradeJsonlWriter implements ApplicationRunner {
 private final LaplaceTradeEventRepository repository;private final ObjectMapper mapper;private final LaplaceStrategyProperties properties;
 @Override public void run(ApplicationArguments args){drain();}
 @Transactional public synchronized void drain(){for(var event:repository.findTop100ByJsonlWrittenFalseOrderByCreatedAtAsc())try{Path dir=Path.of(properties.getLaplace().getDiagnosticDirectory());Files.createDirectories(dir);Path file=dir.resolve("laplace-trades-"+java.time.LocalDate.now()+".jsonl");String existing=Files.exists(file)?Files.readString(file):"";if(!existing.contains("\"eventId\":\""+event.getEventId()+"\""))Files.writeString(file,event.getPayloadJson()+System.lineSeparator(),StandardOpenOption.CREATE,StandardOpenOption.APPEND);event.setJsonlWritten(true);event.setWrittenAt(Instant.now());repository.save(event);}catch(Exception e){log.error("JSONL_WRITE_FAILED eventId={} symbol={} errorMessage={}",event.getEventId(),event.getSymbol(),e.getMessage());return;}}
 public Optional<String> tryJson(Object value){try{return Optional.of(mapper.writeValueAsString(value));}catch(Exception e){log.error("LAPLACE_TRADE_EVENT_SERIALIZATION_FAILED errorType={} errorMessage={}",e.getClass().getSimpleName(),e.getMessage());return Optional.empty();}}
 public String json(Object value){return tryJson(value).orElseThrow(()->new IllegalStateException("JSON serialization failed"));}
 @Transactional public boolean failure(String symbol,Instant candle,String currentPosition,String action,String reason,Throwable error,boolean retryable){String id=UUID.randomUUID().toString();Map<String,Object> payload=new LinkedHashMap<>();payload.put("eventType","FAILURE");payload.put("eventId",id);payload.put("strategy",LaplacePaperExecutionService.STRATEGY);payload.put("symbol",symbol);payload.put("signalCandleCloseTime",candle);payload.put("currentPosition",currentPosition);payload.put("requestedAction",action);payload.put("failureReason",reason);payload.put("errorType",error==null?null:error.getClass().getSimpleName());payload.put("errorMessage",error==null?null:error.getMessage());payload.put("retryable",retryable);payload.put("failureTime",Instant.now());try{String json=mapper.writeValueAsString(payload);repository.save(LaplaceTradeEventEntity.builder().eventId(id).eventType("FAILURE").symbol(symbol).payloadJson(json).jsonlWritten(false).createdAt(Instant.now()).build());log.info("LAPLACE_FAILURE_EVENT_PUBLISHED eventId={} failureReason={} symbol={}",id,reason,symbol);return true;}catch(Exception serializationOrPersistence){log.error("LAPLACE_FAILURE_EVENT_SERIALIZATION_FAILED strategy={} symbol={} signalCandleCloseTime={} requestedAction={} originalFailureReason={} originalErrorType={} originalErrorMessage={} serializationErrorType={} serializationErrorMessage={}",LaplacePaperExecutionService.STRATEGY,symbol,String.valueOf(candle),action,reason,error==null?null:error.getClass().getSimpleName(),error==null?null:error.getMessage(),serializationOrPersistence.getClass().getSimpleName(),serializationOrPersistence.getMessage());return false;}}
}
