package com.crypto.laplace.execution;

import com.crypto.common.enums.PositionSide;
import com.crypto.domain.model.Kline;
import com.crypto.laplace.model.*;
import com.crypto.laplace.persistence.*;
import com.crypto.laplace.service.StartupMarketUniverseService;
import com.crypto.laplace.config.LaplaceStrategyProperties;
import java.math.*;import java.time.*;import java.util.*;
import lombok.RequiredArgsConstructor;import lombok.extern.slf4j.Slf4j;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Slf4j @Service @RequiredArgsConstructor
public class LaplacePaperExecutionService {
 public static final String STRATEGY="LAPLACE_KERNEL_REGRESSION_30M", VERSION="1.0";private static final int SCALE=12;private static final BigDecimal STOP_LOSS_PCT=new BigDecimal("0.044");
 private final LaplacePaperPositionRepository positions;private final LaplaceTradeEventRepository events;private final LaplaceExecutionPriceProvider prices;private final LaplacePnlCalculator pnl;private final LaplaceStrategyProperties properties;private final LaplaceTradeJsonlWriter writer;
 private final StartupMarketUniverseService universe;
 @Transactional public LaplacePaperPositionEntity open(LaplaceSignalResult signal,PositionSide side,String reversalId,String positionBefore){
  assertNoOpen(signal.symbol());MarketExecutionAction action=side==PositionSide.LONG?MarketExecutionAction.LONG_OPEN:MarketExecutionAction.SHORT_OPEN;var quote=prices.quote(signal.symbol(),action);Instant requested=Instant.now();BigDecimal price=quote.value();BigDecimal notional=properties.getLaplace().getNotionalUsdt();int leverage=properties.getLaplace().getLeverage();BigDecimal margin=properties.getLaplace().getMarginPerPositionUsdt();BigDecimal quantity=notional.divide(price,SCALE,RoundingMode.DOWN);BigDecimal feeRate=properties.getLaplace().getTakerFeeRate();
  if(quantity.signum()<=0)throw new IllegalStateException("INVALID_QUANTITY");if(!hasAvailableBalance(margin.add(notional.multiply(feeRate))))throw new IllegalStateException("INSUFFICIENT_PAPER_BALANCE");BigDecimal fee=notional.multiply(feeRate).setScale(SCALE,RoundingMode.HALF_UP);String signalId=entryKey(signal,side);Instant now=Instant.now();
  var p=LaplacePaperPositionEntity.builder().id(UUID.randomUUID().toString()).strategy(STRATEGY).strategyVersion(VERSION).symbol(signal.symbol()).side(side).status(LaplacePositionStatus.OPEN).entrySignalId(signalId).entryRawSignal(signal.entrySignal().name()).signalInverted(true).entryCandleCloseTime(signal.signalCandleCloseTime()).entryTime(now).entrySignalClosePrice(BigDecimal.valueOf(signal.signalCandleClose())).entryExecutionPrice(price).margin(margin).quantity(quantity).initialQuantity(quantity).remainingQuantity(quantity).tp1Executed(false).tp2Executed(false).notional(notional).leverage(leverage).entryFeeRate(feeRate).entryFee(fee).build();positions.saveAndFlush(p);
  log.info("LAPLACE_MARKET_ENTRY_EXECUTED strategy={} symbol={} side={} orderType=MARKET executionPriceType={} executionPrice={} notional={} leverage={}",STRATEGY,signal.symbol(),side,quote.executionPriceType(),price,notional,leverage);
  Map<String,Object> payload=base(signal,"ENTRY",p,UUID.randomUUID().toString(),reversalId);payload.put("side",side);payload.put("rawEntrySignal",signal.entrySignal());payload.put("rawStrongReversalSignal",signal.strongReversalSignal());payload.put("effectiveExecutionSide",side);payload.put("signalInverted",true);payload.put("initialCapitalUsdt",properties.getLaplace().getInitialCapitalUsdt());payload.put("positionBefore",positionBefore);payload.put("positionAfter",side);payload.put("entryReason",reversalId==null?"CONFIRMED_LAPLACE_"+side:"CONFIRMED_LAPLACE_REVERSAL");payload.put("signalDetectedAt",requested);payload.put("executionRequestedAt",requested);payload.put("executionTime",now);payload.put("orderType","MARKET");payload.put("executionAction",action);payload.put("priceSource",quote.source());payload.put("bestBid",quote.bestBid());payload.put("bestAsk",quote.bestAsk());payload.put("executionPriceType",quote.executionPriceType());payload.put("executionPrice",price);payload.put("margin",margin);payload.put("leverage",leverage);payload.put("notional",notional);payload.put("quantity",quantity);payload.put("takerFeeRate",feeRate);payload.put("entryFeeRate",feeRate);payload.put("entryFee",fee);payload.put("status",p.getStatus());saveEvent(payload,"ENTRY",reversalId,p);return p;
 }
 @Transactional public ReversalOutcome reverse(LaplaceSignalResult signal,LaplacePaperPositionEntity expected,PositionSide target,boolean openTarget){
  LaplacePaperPositionEntity p=singleOpenForUpdate(signal.symbol());if(!p.getId().equals(expected.getId()))throw new IllegalStateException("POSITION_STATE_CONFLICT");String exitSignalId=reversalKey(signal,target);if(p.getExitSignalId()!=null)throw new IllegalStateException("DUPLICATE_EXECUTION_BLOCKED");String reversalId=UUID.randomUUID().toString();Instant requested=Instant.now();MarketExecutionAction action=p.getSide()==PositionSide.LONG?MarketExecutionAction.LONG_CLOSE:MarketExecutionAction.SHORT_CLOSE;var quote=prices.quote(signal.symbol(),action);Instant now=Instant.now();BigDecimal exitNotional=p.getQuantity().multiply(quote.value()).setScale(SCALE,RoundingMode.HALF_UP);BigDecimal exitFee=exitNotional.multiply(p.getEntryFeeRate()).setScale(SCALE,RoundingMode.HALF_UP);var result=pnl.calculate(p.getSide(),p.getEntryExecutionPrice(),quote.value(),p.getQuantity(),p.getNotional(),p.getEntryFee(),exitFee);
  if(p.getLeverage()!=20||p.getNotional().compareTo(new BigDecimal("100"))!=0)log.warn("LAPLACE_LEGACY_POSITION_SIZING_PRESERVED symbol={} positionId={} notional={} leverage={}",p.getSymbol(),p.getId(),p.getNotional(),p.getLeverage());
  p.setStatus(LaplacePositionStatus.CLOSED);p.setExitSignalId(exitSignalId);p.setExitTime(now);p.setExitExecutionPrice(quote.value());p.setExitFee(exitFee);p.setGrossPnl(result.gross());p.setGrossPnlPct(result.grossPct());p.setNetPnl(result.net());p.setNetPnlPct(result.netPct());p.setHoldingMinutes(Duration.between(p.getEntryTime(),now).toMinutes());p.setExitReason(openTarget?"OPPOSITE_CONFIRMED_LAPLACE_SIGNAL":"OPPOSITE_SIGNAL_OUTSIDE_ENTRY_UNIVERSE");positions.saveAndFlush(p);
  log.info("LAPLACE_MARKET_EXIT_EXECUTED strategy={} symbol={} side={} orderType=MARKET executionPriceType={} executionPrice={} entryNotional={} leverage={}",STRATEGY,signal.symbol(),p.getSide(),quote.executionPriceType(),quote.value(),p.getNotional(),p.getLeverage());
  Map<String,Object> payload=base(signal,"EXIT",p,UUID.randomUUID().toString(),reversalId);payload.put("side",p.getSide());payload.put("closedSide",p.getSide());payload.put("incomingSignal",target);payload.put("positionBefore",p.getSide());payload.put("positionAfter","FLAT");payload.put("exitReason",p.getExitReason());payload.put("entryTime",p.getEntryTime());payload.put("entrySignalClosePrice",p.getEntrySignalClosePrice());payload.put("entryExecutionPrice",p.getEntryExecutionPrice());payload.put("exitExecutionRequestedAt",requested);payload.put("exitTime",now);payload.put("orderType","MARKET");payload.put("executionAction",action);payload.put("priceSource",quote.source());payload.put("bestBid",quote.bestBid());payload.put("bestAsk",quote.bestAsk());payload.put("executionPriceType",quote.executionPriceType());payload.put("exitExecutionPrice",quote.value());payload.put("entryNotional",p.getNotional());payload.put("exitNotional",exitNotional);payload.put("quantity",p.getQuantity());payload.put("notional",p.getNotional());payload.put("leverage",p.getLeverage());payload.put("grossPnl",p.getGrossPnl());payload.put("grossPnlPct",p.getGrossPnlPct());payload.put("entryFee",p.getEntryFee());payload.put("takerFeeRate",p.getEntryFeeRate());payload.put("exitFeeRate",p.getEntryFeeRate());payload.put("exitFee",exitFee);payload.put("totalFee",p.getEntryFee().add(exitFee));payload.put("netPnl",p.getNetPnl());payload.put("netPnlPct",p.getNetPnlPct());payload.put("holdingMinutes",p.getHoldingMinutes());payload.put("status",p.getStatus());saveEvent(payload,"EXIT",reversalId,p);
  LaplacePaperPositionEntity opened=null;if(openTarget)try{opened=open(signal,target,reversalId,p.getSide().name());}catch(RuntimeException failure){throw new IllegalStateException("REVERSAL_OPEN_FAILED",failure);}return new ReversalOutcome(p,opened,reversalId);
 }
 @Transactional public void closeStopLosses(Map<String,Kline> candles){for(var position:positions.findByStrategyAndStatus(STRATEGY,LaplacePositionStatus.OPEN))closeStopLossIfHit(position.getSymbol(),candles.get(position.getSymbol()));}
 @Transactional public void executeTakeProfits(Map<String,Kline> candles){for(var position:positions.findByStrategyAndStatus(STRATEGY,LaplacePositionStatus.OPEN))executeTakeProfits(position.getSymbol(),candles.get(position.getSymbol()));}
 private void executeTakeProfits(String symbol,Kline candle){if(candle==null||candle.getHigh()==null||candle.getLow()==null)return;List<LaplacePaperPositionEntity> open=positions.findOpenForUpdate(STRATEGY,symbol,LaplacePositionStatus.OPEN);if(open.size()!=1)return;LaplacePaperPositionEntity p=open.get(0);BigDecimal entry=p.getEntryExecutionPrice();BigDecimal tp1=p.getSide()==PositionSide.LONG?entry.multiply(new BigDecimal("1.05")):entry.multiply(new BigDecimal("0.95"));BigDecimal tp2=p.getSide()==PositionSide.LONG?entry.multiply(new BigDecimal("1.10")):entry.multiply(new BigDecimal("0.90"));boolean hit1=p.getSide()==PositionSide.LONG?candle.getHigh().compareTo(tp1)>=0:candle.getLow().compareTo(tp1)<=0;boolean hit2=p.getSide()==PositionSide.LONG?candle.getHigh().compareTo(tp2)>=0:candle.getLow().compareTo(tp2)<=0;if(hit2&&!Boolean.TRUE.equals(p.getTp1Executed()))partialTakeProfit(p,tp1,new BigDecimal("0.25"),true,candle);else if(hit1&&!Boolean.TRUE.equals(p.getTp1Executed()))partialTakeProfit(p,tp1,new BigDecimal("0.25"),true,candle);if(hit2&&!Boolean.TRUE.equals(p.getTp2Executed()))partialTakeProfit(p,tp2,new BigDecimal("0.50"),false,candle);}
 private void partialTakeProfit(LaplacePaperPositionEntity p,BigDecimal price,BigDecimal fraction,boolean tp1,Kline candle){BigDecimal initial=defaultQuantity(p);BigDecimal remaining=remainingQuantity(p);BigDecimal closed=(tp1?initial:remaining).multiply(fraction).setScale(SCALE,RoundingMode.DOWN);if(closed.signum()<=0)return;BigDecimal exitNotional=closed.multiply(price).setScale(SCALE,RoundingMode.HALF_UP);BigDecimal exitFee=exitNotional.multiply(p.getEntryFeeRate()).setScale(SCALE,RoundingMode.HALF_UP);BigDecimal entryFee=p.getEntryFee().multiply(closed).divide(initial,SCALE,RoundingMode.HALF_UP);var result=pnl.calculate(p.getSide(),p.getEntryExecutionPrice(),price,closed,p.getNotional().multiply(closed).divide(initial,SCALE,RoundingMode.HALF_UP),entryFee,exitFee);p.setRemainingQuantity(remaining.subtract(closed));p.setQuantity(p.getRemainingQuantity());String eventType=tp1?"PARTIAL_TP1":"PARTIAL_TP2";if(tp1){p.setTp1Executed(true);p.setTp1ClosedQuantity(closed);p.setTp1RealizedPnl(result.net());}else{p.setTp2Executed(true);p.setTp2ClosedQuantity(closed);p.setTp2RealizedPnl(result.net());}positions.saveAndFlush(p);Map<String,Object> payload=new LinkedHashMap<>();payload.put("eventType",eventType);payload.put("eventId",UUID.randomUUID().toString());payload.put("strategy",STRATEGY);payload.put("strategyVersion",VERSION);payload.put("positionId",p.getId());payload.put("symbol",p.getSymbol());payload.put("side",p.getSide());payload.put("entryPrice",p.getEntryExecutionPrice());payload.put("tpPrice",price);payload.put("initialQuantity",initial);payload.put("closedQuantity",closed);payload.put("remainingQuantity",p.getRemainingQuantity());payload.put("profitPct",tp1?5.0:10.0);payload.put("realizedGrossPnl",result.gross());payload.put("fee",exitFee);payload.put("realizedNetPnl",result.net());payload.put("candleOpenTime",candle.getOpenTime());payload.put("candleHigh",candle.getHigh());payload.put("candleLow",candle.getLow());savePartialTakeProfitEvent(payload,eventType,p);log.info("{}_EXECUTED symbol={} side={} entryPrice={} tpPrice={} initialQuantity={} closedQuantity={} remainingQuantity={} realizedGrossPnl={} fee={} realizedNetPnl={} candleOpenTime={} candleHigh={} candleLow={}",eventType,p.getSymbol(),p.getSide(),p.getEntryExecutionPrice(),price,initial,closed,p.getRemainingQuantity(),result.gross(),exitFee,result.net(),candle.getOpenTime(),candle.getHigh(),candle.getLow());}
 private BigDecimal defaultQuantity(LaplacePaperPositionEntity p){return p.getInitialQuantity()==null?p.getQuantity():p.getInitialQuantity();}
 private BigDecimal remainingQuantity(LaplacePaperPositionEntity p){return p.getRemainingQuantity()==null?p.getQuantity():p.getRemainingQuantity();}
 private void closeStopLossIfHit(String symbol,Kline candle){if(candle==null||candle.getHigh()==null||candle.getLow()==null)return;List<LaplacePaperPositionEntity> open=positions.findOpenForUpdate(STRATEGY,symbol,LaplacePositionStatus.OPEN);if(open.size()!=1)return;LaplacePaperPositionEntity p=open.get(0);BigDecimal stop=stopLossPrice(p);boolean hit=p.getSide()==PositionSide.LONG?candle.getLow().compareTo(stop)<=0:candle.getHigh().compareTo(stop)>=0;if(!hit)return;Instant now=Instant.now();BigDecimal exitNotional=p.getQuantity().multiply(stop).setScale(SCALE,RoundingMode.HALF_UP);BigDecimal exitFee=exitNotional.multiply(p.getEntryFeeRate()).setScale(SCALE,RoundingMode.HALF_UP);var result=pnl.calculate(p.getSide(),p.getEntryExecutionPrice(),stop,p.getQuantity(),p.getNotional(),p.getEntryFee(),exitFee);p.setStatus(LaplacePositionStatus.CLOSED);p.setExitSignalId("STOP_LOSS:"+p.getId());p.setExitTime(now);p.setExitExecutionPrice(stop);p.setExitFee(exitFee);p.setGrossPnl(result.gross());p.setGrossPnlPct(result.grossPct());p.setNetPnl(result.net());p.setNetPnlPct(result.netPct());p.setHoldingMinutes(Duration.between(p.getEntryTime(),now).toMinutes());p.setExitReason("STOP_LOSS");positions.saveAndFlush(p);Map<String,Object> payload=new LinkedHashMap<>();payload.put("eventType","EXIT");payload.put("eventId",UUID.randomUUID().toString());payload.put("strategy",STRATEGY);payload.put("strategyVersion",VERSION);payload.put("positionId",p.getId());payload.put("symbol",p.getSymbol());payload.put("side",p.getSide());payload.put("exitReason","STOP_LOSS");payload.put("exitExecutionPrice",stop);payload.put("stopLossPrice",stop);payload.put("status",p.getStatus());saveStopLossEvent(payload,p);log.info("LAPLACE_STOP_LOSS_EXECUTED strategy={} symbol={} side={} candleHigh={} candleLow={} stopLossPrice={}",STRATEGY,symbol,p.getSide(),candle.getHigh(),candle.getLow(),stop);}
 private BigDecimal stopLossPrice(LaplacePaperPositionEntity p){return p.getSide()==PositionSide.LONG?p.getEntryExecutionPrice().multiply(BigDecimal.ONE.subtract(STOP_LOSS_PCT)):p.getEntryExecutionPrice().multiply(BigDecimal.ONE.add(STOP_LOSS_PCT));}
 boolean hasAvailableBalance(BigDecimal required){return availableBalance().compareTo(required)>=0;}
 BigDecimal availableBalance(){BigDecimal realized=positions.findByStrategyAndStatus(STRATEGY,LaplacePositionStatus.CLOSED).stream().map(x->x.getNetPnl()==null?BigDecimal.ZERO:x.getNetPnl()).reduce(BigDecimal.ZERO,BigDecimal::add);List<LaplacePaperPositionEntity> open=positions.findByStrategyAndStatus(STRATEGY,LaplacePositionStatus.OPEN);BigDecimal locked=open.stream().map(LaplacePaperPositionEntity::getMargin).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal openEntryFees=open.stream().map(x->x.getEntryFee()==null?BigDecimal.ZERO:x.getEntryFee()).reduce(BigDecimal.ZERO,BigDecimal::add);return properties.getLaplace().getInitialCapitalUsdt().add(realized).subtract(locked).subtract(openEntryFees);}
 private void assertNoOpen(String symbol){if(!positions.findOpenForUpdate(STRATEGY,symbol,LaplacePositionStatus.OPEN).isEmpty())throw new IllegalStateException("POSITION_STATE_CONFLICT");}
 public LaplacePaperPositionEntity singleOpenForUpdate(String symbol){List<LaplacePaperPositionEntity>x=positions.findOpenForUpdate(STRATEGY,symbol,LaplacePositionStatus.OPEN);if(x.size()!=1)throw new IllegalStateException("POSITION_STATE_CONFLICT");return x.get(0);}
 private void saveEvent(Map<String,Object> payload,String type,String reversal,LaplacePaperPositionEntity p){String id=(String)payload.get("eventId");writer.tryJson(payload).ifPresentOrElse(json->{events.save(LaplaceTradeEventEntity.builder().eventId(id).eventType(type).reversalId(reversal).positionId(p.getId()).symbol(p.getSymbol()).payloadJson(json).jsonlWritten(false).createdAt(Instant.now()).build());log.info("LAPLACE_TRADE_EVENT_PUBLISHED eventId={} eventType={} symbol={}",id,type,p.getSymbol());},()->log.error("LAPLACE_TRADE_EVENT_SERIALIZATION_SKIPPED eventId={} eventType={} symbol={} positionId={}",id,type,p.getSymbol(),p.getId()));}
 private void saveStopLossEvent(Map<String,Object> payload,LaplacePaperPositionEntity p){String id=(String)payload.get("eventId");writer.tryJson(payload).ifPresentOrElse(json->events.save(LaplaceTradeEventEntity.builder().eventId(id).eventType("EXIT").positionId(p.getId()).symbol(p.getSymbol()).payloadJson(json).jsonlWritten(false).createdAt(Instant.now()).build()),()->log.error("LAPLACE_STOP_LOSS_EVENT_SERIALIZATION_SKIPPED positionId={}",p.getId()));}
 private void savePartialTakeProfitEvent(Map<String,Object> payload,String eventType,LaplacePaperPositionEntity p){String id=(String)payload.get("eventId");writer.tryJson(payload).ifPresentOrElse(json->events.save(LaplaceTradeEventEntity.builder().eventId(id).eventType(eventType).positionId(p.getId()).symbol(p.getSymbol()).payloadJson(json).jsonlWritten(false).createdAt(Instant.now()).build()),()->log.error("LAPLACE_PARTIAL_TP_EVENT_SERIALIZATION_SKIPPED positionId={} eventType={}",p.getId(),eventType));}
 private Map<String,Object> base(LaplaceSignalResult s,String type,LaplacePaperPositionEntity p,String eventId,String reversal){Map<String,Object>m=new LinkedHashMap<>();m.put("eventType",type);m.put("eventId",eventId);m.put("reversalId",reversal);m.put("strategy",STRATEGY);m.put("strategyVersion",VERSION);m.put("positionId",p.getId());m.put("symbol",s.symbol());m.put("timeframe",s.timeframe());m.put("kernel",s.kernel());m.put("bandwidth",s.bandwidth());m.put("source",s.source());m.put("repaint",s.repaint());m.put("startupUniverseSessionId",universe.sessionId());m.put("startupVolumeValue",universe.startupVolume(s.symbol()));m.put("minimumVolumeThreshold",universe.minimumVolumeThreshold());m.put("inStartupEntryUniverse",universe.symbols().contains(s.symbol()));m.put("signalCandleOpenTime",s.signalCandleOpenTime());m.put("signalCandleCloseTime",s.signalCandleCloseTime());m.put("signalCandleClose",s.signalCandleClose());m.put("regressionCurrent",s.regressionCurrent());m.put("regressionPrevious",s.regressionPrevious());m.put("regressionTwoBarsAgo",s.regressionTwoBarsAgo());m.put("currentSlope",s.currentSlope());m.put("previousSlope",s.previousSlope());m.put("currentAtr14",s.currentAtr14());m.put("previousAtr14",s.previousAtr14());m.put("currentNormalizedSlope",s.currentNormalizedSlope());m.put("previousNormalizedSlope",s.previousNormalizedSlope());m.put("entryThreshold",s.entryThreshold());m.put("reversalThreshold",s.reversalThreshold());m.put("confirmationBars",s.confirmationBars());m.put("entrySignal",s.entrySignal());m.put("strongReversalSignal",s.strongReversalSignal());m.put("rawEntrySignal",s.entrySignal());m.put("rawStrongReversalSignal",s.strongReversalSignal());m.put("signalInverted",true);return m;}
 public static String entryKey(LaplaceSignalResult s,PositionSide side){return STRATEGY+":"+s.symbol()+":"+s.signalCandleCloseTime()+":ENTRY:"+side;}public static String reversalKey(LaplaceSignalResult s,PositionSide side){return STRATEGY+":"+s.symbol()+":"+s.signalCandleCloseTime()+":REVERSAL:"+side;}
 public record ReversalOutcome(LaplacePaperPositionEntity closed,LaplacePaperPositionEntity opened,String reversalId){}
}
