package com.crypto.laplace.execution;

public enum VolumeProfileRejectionReason {
    VP_INSIDE_LONG_ABOVE_POC,
    VP_INSIDE_LONG_DELTA_NOT_SELLING,
    VP_INSIDE_SHORT_BELOW_POC,
    VP_INSIDE_SHORT_DELTA_NOT_BUYING,
    VP_OUTSIDE_LONG_NO_BUY_CONFIRMATION,
    VP_OUTSIDE_SHORT_NO_SELL_CONFIRMATION,
    VP_LONG_ABOVE_SESSION_HIGH,
    VP_SHORT_BELOW_SESSION_LOW,
    VP_PROFILE_NOT_AVAILABLE,
    VP_INSUFFICIENT_60M_DATA
}
