package com.crypto.laplace.pool;
import com.crypto.binance.client.BinanceFuturesClient; import com.crypto.domain.model.*; import com.crypto.laplace.execution.LaplacePaperExecutionService; import com.crypto.laplace.model.LaplacePositionStatus; import com.crypto.laplace.persistence.LaplacePaperPositionRepository; import java.math.*; import java.time.*; import java.util.*; import lombok.*; import lombok.extern.slf4j.Slf4j; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Slf4j @Service @RequiredArgsConstructor public class LaplaceCoinPoolService {
 static final BigDecimal ENTRY_THRESHOLD=new BigDecimal("25000000"), EXIT_THRESHOLD=new BigDecimal("20000000"), INITIAL_CAPITAL=new BigDecimal("250"), INITIAL_MARGIN=new BigDecimal("5");
 private final BinanceFuturesClient client; private final LaplaceCoinPoolRepository pool; private final LaplacePaperPositionRepository positions; private final LaplaceCapitalSnapshotRepository snapshots;
 public boolean canOpen(String symbol){return pool.findById(symbol).map(p->p.getState()==LaplaceCoinPoolState.ACTIVE).orElse(false);}
 public Set<String> symbolsToProcess(){return new HashSet<>(pool.findByStateIn(List.of(LaplaceCoinPoolState.ACTIVE,LaplaceCoinPoolState.WAITING_FOR_NEW_TREND,LaplaceCoinPoolState.PENDING_REMOVAL)).stream().map(LaplaceCoinPoolEntity::getSymbol).toList());}
 public BigDecimal dailyMargin(){return snapshots.findById(LocalDate.now(ZoneId.of("America/New_York"))).map(LaplaceCapitalSnapshotEntity::getDailyTradeMargin).orElse(INITIAL_MARGIN);}
 @Transactional public void scan(){ List<SymbolInfo> info=client.getExchangeInfo(); List<Ticker24h> ticker=client.getAll24hTickers(); if(info==null||ticker==null) throw new IllegalStateException("POOL_MARKET_DATA_UNAVAILABLE"); Set<String> eligible=new HashSet<>(); for(SymbolInfo s:info)if(s!=null&&"USDT".equals(s.getQuoteAsset())&&"PERPETUAL".equals(s.getContractType())&&"TRADING".equals(s.getStatus()))eligible.add(s.getSymbol()); Map<String,BigDecimal> volumes=new HashMap<>();for(Ticker24h t:ticker)if(t!=null&&eligible.contains(t.getSymbol())&&t.getQuoteVolume()!=null)volumes.put(t.getSymbol(),t.getQuoteVolume()); Instant now=Instant.now(); for(LaplaceCoinPoolEntity p:pool.findAll()){BigDecimal v=volumes.get(p.getSymbol());if(v==null){log.warn("LAPLACE_POOL_VOLUME_MISSING symbol={} state={}",p.getSymbol(),p.getState());continue;}p.setLastQuoteVolume(v);p.setLastVolumeScanAt(now);if(p.getState()==LaplaceCoinPoolState.PENDING_REMOVAL)continue;if(p.getState()!=LaplaceCoinPoolState.REMOVED&&v.compareTo(EXIT_THRESHOLD)<0){transition(p,hasOpen(p.getSymbol())?LaplaceCoinPoolState.PENDING_REMOVAL:LaplaceCoinPoolState.REMOVED);}}
 for(var e:volumes.entrySet()){LaplaceCoinPoolEntity p=pool.findById(e.getKey()).orElse(null);if((p==null||p.getState()==LaplaceCoinPoolState.REMOVED)&&e.getValue().compareTo(ENTRY_THRESHOLD)>0){if(p==null)p=LaplaceCoinPoolEntity.builder().symbol(e.getKey()).build();p.setLastQuoteVolume(e.getValue());p.setLastVolumeScanAt(now);p.setAddedAt(now);p.setRemovedAt(null);p.setPendingRemovalAt(null);p.setWaitingForNewTrend(true);transition(p,LaplaceCoinPoolState.WAITING_FOR_NEW_TREND);pool.save(p);}}
 BigDecimal realized=INITIAL_CAPITAL.add(positions.findAll().stream().filter(x->LaplacePaperExecutionService.STRATEGY.equals(x.getStrategy()) && x.getStatus()!=LaplacePositionStatus.OPEN).map(x->x.getNetPnl()==null?BigDecimal.ZERO:x.getNetPnl()).reduce(BigDecimal.ZERO,BigDecimal::add)); BigDecimal margin=INITIAL_MARGIN.multiply(realized.divide(INITIAL_CAPITAL,12,RoundingMode.HALF_UP)); snapshots.save(LaplaceCapitalSnapshotEntity.builder().snapshotDate(LocalDate.now(ZoneId.of("America/New_York"))).realizedCapital(realized).dailyTradeMargin(margin).leverage(10).positionNotional(margin.multiply(BigDecimal.TEN)).calculatedAt(now).build()); log.info("LAPLACE_POOL_SCAN completed symbols={} volumes={} realizedCapital={} dailyTradeMargin={}",eligible.size(),volumes,realized,margin); }
 @Transactional public boolean observeTrend(String symbol,LaplaceTrend trend){var p=pool.findById(symbol).orElse(null);if(p==null||p.getState()!=LaplaceCoinPoolState.WAITING_FOR_NEW_TREND)return p!=null&&p.getState()==LaplaceCoinPoolState.ACTIVE; LaplaceTrend previous=p.getLastObservedTrend();p.setLastObservedTrend(trend);if(previous!=null&&previous!=trend&&trend!=LaplaceTrend.NEUTRAL){transition(p,LaplaceCoinPoolState.ACTIVE);p.setWaitingForNewTrend(false);log.info("LAPLACE_TREND_LOCK_RELEASED symbol={} previousTrend={} currentTrend={} poolState=ACTIVE",symbol,previous,trend);return true;}log.info("LAPLACE_TREND_LOCK_WAITING symbol={} previousTrend={} currentTrend={} entryBlockedReason=WAITING_FOR_NEW_TREND",symbol,previous,trend);return false; }
 @Transactional public void baseline(String symbol,LaplaceTrend trend){pool.findById(symbol).filter(p->p.getState()==LaplaceCoinPoolState.WAITING_FOR_NEW_TREND&&p.getLastObservedTrend()==null).ifPresent(p->{p.setLastObservedTrend(trend);pool.save(p);});}
 @Transactional public void positionClosed(String symbol){pool.findById(symbol).filter(p->p.getState()==LaplaceCoinPoolState.PENDING_REMOVAL).ifPresent(p->transition(p,LaplaceCoinPoolState.REMOVED));}
 private boolean hasOpen(String symbol){return !positions.findByStrategyAndSymbolAndStatus(LaplacePaperExecutionService.STRATEGY,symbol,LaplacePositionStatus.OPEN).isEmpty();} private void transition(LaplaceCoinPoolEntity p,LaplaceCoinPoolState next){LaplaceCoinPoolState old=p.getState();p.setState(next);Instant n=Instant.now();if(next==LaplaceCoinPoolState.REMOVED)p.setRemovedAt(n);if(next==LaplaceCoinPoolState.PENDING_REMOVAL)p.setPendingRemovalAt(n);pool.save(p);log.info("LAPLACE_POOL_STATE_CHANGED symbol={} previousState={} state={}",p.getSymbol(),old,next);}
}
