package com.crypto.laplace.api;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.*;
import com.crypto.binance.client.BinanceFuturesClient;
import com.crypto.common.enums.PositionSide;
import com.crypto.domain.model.BookTicker;
import com.crypto.laplace.execution.*;
import com.crypto.laplace.model.*;
import com.crypto.laplace.persistence.*;
import com.crypto.laplace.service.*;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class LaplaceDualSummaryServiceTest {
 private LaplacePaperPositionRepository tr;private LaplaceInvertedFalsePositionRepository fr;private LaplaceRuntimeService rt;private LaplaceInvertedFalseRuntimeService rf;private BinanceFuturesClient binance;private LaplaceDualSummaryService service;
 @BeforeEach void setup(){tr=mock(LaplacePaperPositionRepository.class);fr=mock(LaplaceInvertedFalsePositionRepository.class);rt=mock(LaplaceRuntimeService.class);rf=mock(LaplaceInvertedFalseRuntimeService.class);binance=mock(BinanceFuturesClient.class);service=new LaplaceDualSummaryService(tr,fr,rt,rf,binance,new LaplacePnlCalculator());when(tr.findByStrategyAndStatus(any(),any())).thenReturn(List.of());when(fr.findByStrategyAndStatus(any(),any())).thenReturn(List.of());when(rt.current()).thenReturn(trueSession(LaplaceRuntimeState.ACTIVE,"350","5",null,null,null));when(rf.current()).thenReturn(falseSession(LaplaceRuntimeState.ACTIVE,"350","5",null,null,null));}
 @Test void returnsExactlyTrueThenFalseWithInitialRuntimeValues(){var result=service.summaries();assertThat(result).hasSize(2);assertThat(result.get(0).paperVariant()).isEqualTo("INVERTED_TRUE");assertThat(result.get(0).signalInverted()).isTrue();assertThat(result.get(1).paperVariant()).isEqualTo("INVERTED_FALSE");assertThat(result.get(1).signalInverted()).isFalse();assertThat(result).allSatisfy(x->{assertThat(x.currentBalanceUsdt()).isEqualByComparingTo("350");assertThat(x.marginPerPositionUsdt()).isEqualByComparingTo("5");assertThat(x.profitLockDown()).isFalse();assertThat(x.reopenAt()).isNull();});}
 @Test void trueCooldownUsesNextSizingWithoutChangingFalseRuntime(){Instant reopen=Instant.parse("2026-08-15T00:30:00Z");when(rt.current()).thenReturn(trueSession(LaplaceRuntimeState.COOLDOWN,"350","5","367.5","5.25",reopen));var result=service.summaries();assertThat(result.get(0).currentBalanceUsdt()).isEqualByComparingTo("367.5");assertThat(result.get(0).marginPerPositionUsdt()).isEqualByComparingTo("5.25");assertThat(result.get(0).profitLockDown()).isTrue();assertThat(result.get(0).reopenAt()).isEqualTo(reopen);assertThat(result.get(1).runtimeState()).isEqualTo(LaplaceRuntimeState.ACTIVE);assertThat(result.get(1).profitLockDown()).isFalse();assertThat(result.get(1).reopenAt()).isNull();}
 @Test void falseCooldownChangesOnlyFalseRuntimeProjection(){Instant reopen=Instant.parse("2026-08-15T01:30:00Z");when(rf.current()).thenReturn(falseSession(LaplaceRuntimeState.COOLDOWN,"350","5","367.5","5.25",reopen));var result=service.summaries();assertThat(result.get(0).runtimeState()).isEqualTo(LaplaceRuntimeState.ACTIVE);assertThat(result.get(0).profitLockDown()).isFalse();assertThat(result.get(1).currentBalanceUsdt()).isEqualByComparingTo("367.5");assertThat(result.get(1).marginPerPositionUsdt()).isEqualByComparingTo("5.25");assertThat(result.get(1).profitLockDown()).isTrue();assertThat(result.get(1).reopenAt()).isEqualTo(reopen);}
 @Test void statisticsAndCurrentBalanceAreTableAndCurrentSessionIsolatedWithOneTickerCall(){var tc=closedTrue("old",new BigDecimal("99"));var current=closedTrue("ts",new BigDecimal("2"));var fo=openFalse();when(tr.findByStrategyAndStatus(any(),eq(LaplacePositionStatus.CLOSED))).thenReturn(List.of(tc,current));when(fr.findByStrategyAndStatus(any(),eq(LaplacePositionStatus.OPEN))).thenReturn(List.of(fo));when(binance.getAllBookTickers()).thenReturn(List.of(BookTicker.builder().symbol("BTCUSDT").bidPrice(new BigDecimal("110")).askPrice(new BigDecimal("111")).build()));var result=service.summaries();assertThat(result.get(0).tradeCount()).isEqualTo(2);assertThat(result.get(1).tradeCount()).isZero();assertThat(result.get(0).currentBalanceUsdt()).isEqualByComparingTo("352");assertThat(result.get(1).currentBalanceUsdt()).isEqualByComparingTo("359.916000000000");verify(binance,times(1)).getAllBookTickers();verify(rt,never()).beginLiquidation(any(),any(),any(),any());verify(rf,never()).beginLiquidation(any(),any(),any(),any());}
 private LaplaceTradingSessionEntity trueSession(LaplaceRuntimeState s,String capital,String margin,String next,String nextMargin,Instant until){return LaplaceTradingSessionEntity.builder().sessionId("ts").runtimeState(s).sessionStartCapital(bd(capital)).marginPerPosition(bd(margin)).nextSessionCapital(bd(next)).nextMarginPerPosition(bd(nextMargin)).cooldownUntil(until).build();}
 private LaplaceInvertedFalseSessionEntity falseSession(LaplaceRuntimeState s,String capital,String margin,String next,String nextMargin,Instant until){return LaplaceInvertedFalseSessionEntity.builder().sessionId("fs").runtimeState(s).sessionStartCapital(bd(capital)).marginPerPosition(bd(margin)).nextSessionCapital(bd(next)).nextMarginPerPosition(bd(nextMargin)).cooldownUntil(until).build();}
 private LaplacePaperPositionEntity closedTrue(String session,BigDecimal net){return LaplacePaperPositionEntity.builder().sessionId(session).side(PositionSide.LONG).status(LaplacePositionStatus.CLOSED).grossPnl(net).netPnl(net).entryFee(BigDecimal.ZERO).exitFee(BigDecimal.ZERO).netPnlPct(net).entryTime(Instant.parse("2026-08-14T00:00:00Z")).exitTime(Instant.parse("2026-08-14T01:00:00Z")).build();}
 private LaplaceInvertedFalsePositionEntity openFalse(){return LaplaceInvertedFalsePositionEntity.builder().sessionId("fs").symbol("BTCUSDT").side(PositionSide.LONG).status(LaplacePositionStatus.OPEN).entryTime(Instant.parse("2026-08-14T00:00:00Z")).entryExecutionPrice(new BigDecimal("100")).quantity(BigDecimal.ONE).entryFee(new BigDecimal("0.04")).entryFeeRate(new BigDecimal("0.0004")).build();}
 private BigDecimal bd(String x){return x==null?null:new BigDecimal(x);}
}
