package com.crypto.laplace.api;
import static org.assertj.core.api.Assertions.assertThat;import static org.mockito.Mockito.*;import com.crypto.binance.client.BinanceFuturesClient;import com.crypto.common.enums.PositionSide;import com.crypto.laplace.execution.*;import com.crypto.laplace.model.*;import com.crypto.laplace.persistence.*;import com.crypto.laplace.service.LaplaceRuntimeService;import java.math.BigDecimal;import java.time.Instant;import java.util.List;import org.junit.jupiter.api.*;
class LaplaceDualSummaryServiceTest {
 private LaplacePaperPositionRepository positions;private LaplaceRuntimeService runtime;private BinanceFuturesClient binance;private LaplaceDualSummaryService service;
 @BeforeEach void setup(){positions=mock(LaplacePaperPositionRepository.class);runtime=mock(LaplaceRuntimeService.class);binance=mock(BinanceFuturesClient.class);service=new LaplaceDualSummaryService(positions,runtime,binance,new LaplacePnlCalculator());when(positions.findByStrategyAndStatus(any(),any())).thenReturn(List.of());when(runtime.current()).thenReturn(session(LaplaceRuntimeState.ACTIVE,"350","5",null,null,null));}
 @Test void returnsOnlyTrueRuntimeValues(){var result=service.summaries();assertThat(result).singleElement().satisfies(x->{assertThat(x.paperVariant()).isEqualTo("INVERTED_TRUE");assertThat(x.signalInverted()).isTrue();assertThat(x.currentBalanceUsdt()).isEqualByComparingTo("350");assertThat(x.marginPerPositionUsdt()).isEqualByComparingTo("5");});}
 @Test void cooldownUsesCompoundedSizingWithoutReset(){Instant reopen=Instant.parse("2026-08-15T00:30:00Z");when(runtime.current()).thenReturn(session(LaplaceRuntimeState.COOLDOWN,"350","5","367.5","5.25",reopen));var value=service.summaries().getFirst();assertThat(value.currentBalanceUsdt()).isEqualByComparingTo("367.5");assertThat(value.marginPerPositionUsdt()).isEqualByComparingTo("5.25");assertThat(value.reopenAt()).isEqualTo(reopen);verifyNoInteractions(binance);}
 @Test void statisticsUseTrueRepositoryOnly(){when(positions.findByStrategyAndStatus(any(),eq(LaplacePositionStatus.CLOSED))).thenReturn(List.of(closed("old",new BigDecimal("99")),closed("ts",new BigDecimal("2"))));var value=service.summaries().getFirst();assertThat(value.tradeCount()).isEqualTo(2);assertThat(value.currentBalanceUsdt()).isEqualByComparingTo("352");verifyNoInteractions(binance);}
 private LaplaceTradingSessionEntity session(LaplaceRuntimeState state,String capital,String margin,String next,String nextMargin,Instant until){return LaplaceTradingSessionEntity.builder().sessionId("ts").runtimeState(state).sessionStartCapital(bd(capital)).marginPerPosition(bd(margin)).nextSessionCapital(bd(next)).nextMarginPerPosition(bd(nextMargin)).cooldownUntil(until).build();}
 private LaplacePaperPositionEntity closed(String session,BigDecimal net){return LaplacePaperPositionEntity.builder().sessionId(session).side(PositionSide.LONG).status(LaplacePositionStatus.CLOSED).grossPnl(net).netPnl(net).entryFee(BigDecimal.ZERO).exitFee(BigDecimal.ZERO).netPnlPct(net).entryTime(Instant.parse("2026-08-14T00:00:00Z")).exitTime(Instant.parse("2026-08-14T01:00:00Z")).build();}
 private BigDecimal bd(String value){return value==null?null:new BigDecimal(value);}
}
