package com.crypto.laplace.service;
import static org.assertj.core.api.Assertions.assertThat;import static org.mockito.Mockito.*;import com.crypto.common.enums.PositionSide;import com.crypto.domain.model.Kline;import com.crypto.laplace.config.LaplaceStrategyProperties;import com.crypto.laplace.model.*;import java.math.BigDecimal;import java.time.Instant;import java.util.*;import org.junit.jupiter.api.Test;
class LaplaceEntryDecisionServiceTest {
 @Test void rejectsHistoryWhoseLastCandleDoesNotReachSignalCutoff(){var klines=mock(FiveMinuteKlineService.class);var vp=mock(LaplaceVolumeProfileCalculator.class);var properties=new LaplaceStrategyProperties();Instant cutoff=Instant.parse("2026-08-06T10:30:00Z");List<Kline> history=new ArrayList<>();for(int i=0;i<500;i++){Instant close=cutoff.minusSeconds((500L-i)*300);history.add(Kline.builder().closeTime(close).close(BigDecimal.valueOf(100)).low(BigDecimal.valueOf(99)).high(BigDecimal.valueOf(101)).quoteAssetVolume(BigDecimal.ONE).build());}when(klines.loadLastClosedThrough("BTCUSDT",cutoff,500)).thenReturn(history);var decision=new LaplaceEntryDecisionService(klines,vp,properties).evaluate(signal(cutoff),PositionSide.LONG);assertThat(decision.allowed()).isFalse();assertThat(decision.rejectionReasons()).containsExactly(LaplaceEntryRejectionReason.FIVE_MINUTE_HISTORY_UNAVAILABLE);}
 @Test void acceptsBinanceCloseTimestampAndNormalizesExactBoundary(){var klines=mock(FiveMinuteKlineService.class);var vp=mock(LaplaceVolumeProfileCalculator.class);var properties=new LaplaceStrategyProperties();Instant signalCutoff=Instant.parse("2026-08-06T11:00:00Z");Instant expected=Instant.parse("2026-08-06T10:59:59.999Z");List<Kline> history=history(expected);when(klines.loadLastClosedThrough("BTCUSDT",signalCutoff,500)).thenReturn(history);when(klines.lastExpectedClosedFiveMinuteCandle(signalCutoff)).thenReturn(expected);when(vp.calculatePoc(anyList(),eq(36))).thenReturn(100.2);assertThat(new LaplaceEntryDecisionService(klines,vp,properties).evaluate(signal(signalCutoff),PositionSide.LONG).rejectionReasons()).doesNotContain(LaplaceEntryRejectionReason.FIVE_MINUTE_HISTORY_UNAVAILABLE,LaplaceEntryRejectionReason.KURAL5_VOLUME_PROFILE);}

 @Test void blocksExactlyMidnightCandleClose(){assertThat(evaluate("2026-08-07T00:00:00Z",PositionSide.SHORT).rejectionReasons()).contains(LaplaceEntryRejectionReason.BLOCK_5C_0000_UTC);}
 @Test void doesNotBlockHalfPastMidnight(){assertThat(evaluate("2026-08-07T00:30:00Z",PositionSide.SHORT).rejectionReasons()).doesNotContain(LaplaceEntryRejectionReason.BLOCK_5C_0000_UTC);}
 @Test void blocksElevenUtcLongOnly(){assertThat(evaluate("2026-08-07T11:00:00Z",PositionSide.LONG).rejectionReasons()).contains(LaplaceEntryRejectionReason.BLOCK_5C_1100_LONG);assertThat(evaluate("2026-08-07T11:00:00Z",PositionSide.SHORT).rejectionReasons()).doesNotContain(LaplaceEntryRejectionReason.BLOCK_5C_1100_LONG);}
 private LaplaceEntryDecision evaluate(String timestamp,PositionSide side){Instant cutoff=Instant.parse(timestamp),expected=cutoff.minusMillis(1);var klines=mock(FiveMinuteKlineService.class);var vp=mock(LaplaceVolumeProfileCalculator.class);when(klines.loadLastClosedThrough("BTCUSDT",cutoff,500)).thenReturn(history(expected));when(klines.lastExpectedClosedFiveMinuteCandle(cutoff)).thenReturn(expected);when(vp.calculatePoc(anyList(),eq(36))).thenReturn(side==PositionSide.LONG?100.2:99.8);return new LaplaceEntryDecisionService(klines,vp,new LaplaceStrategyProperties()).evaluate(signal(cutoff),side);}
 private List<Kline> history(Instant last){List<Kline>x=new ArrayList<>();for(int i=0;i<500;i++){Instant close=last.minusSeconds((499L-i)*300);x.add(Kline.builder().closeTime(close).close(BigDecimal.valueOf(100)).low(BigDecimal.valueOf(99.9)).high(BigDecimal.valueOf(100.3)).quoteAssetVolume(BigDecimal.ONE).build());}return x;}
 private LaplaceSignalResult signal(Instant close){return new LaplaceSignalResult("LAPLACE_KERNEL_REGRESSION_30M","KURAL5_V1","BTCUSDT","30m","LAPLACE",14,"CLOSE",false,close.minusSeconds(1800),close,100,100,100,100,1,1,1,1,.01,.01,.03,.04,2,LaplaceSignal.SHORT,LaplaceSignal.NONE,StartupState.ACTIVE,1,true,List.of());}
}
