ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS bid_price NUMERIC(30,12);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS ask_price NUMERIC(30,12);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS mid_price NUMERIC(30,12);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS initial_stop NUMERIC(30,12);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS current_stop NUMERIC(30,12);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS risk_per_unit NUMERIC(30,12);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS tp1 NUMERIC(30,12);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS tp2 NUMERIC(30,12);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS tp1_hit BOOLEAN DEFAULT false;
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS tp2_hit BOOLEAN DEFAULT false;
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS trailing_active BOOLEAN DEFAULT false;
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS trailing_activated_at_bar_close_time TIMESTAMPTZ;
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS remaining_position_pct NUMERIC(20,8);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS highest_price_since_entry NUMERIC(30,12);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS lowest_price_since_entry NUMERIC(30,12);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS bars_in_position INTEGER;
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS entry_price_adjusted NUMERIC(30,12);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS exit_price_adjusted NUMERIC(30,12);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS raw_realized_pnl_pct NUMERIC(20,8);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS net_realized_pnl_pct NUMERIC(20,8);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS leveraged_net_realized_pnl_pct NUMERIC(20,8);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS raw_unrealized_pnl_pct NUMERIC(20,8);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS net_unrealized_pnl_pct NUMERIC(20,8);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS leveraged_net_unrealized_pnl_pct NUMERIC(20,8);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS total_fee_pct NUMERIC(20,8);
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS total_slippage_pct NUMERIC(20,8);
