package com.crypto.laplace.session;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.*;
import com.crypto.common.enums.PositionSide;
import com.crypto.laplace.config.LaplaceStrategyProperties;
import com.crypto.laplace.execution.*;
import com.crypto.laplace.model.*;
import com.crypto.laplace.persistence.*;
import com.crypto.laplace.scheduler.LaplaceThirtyMinuteScheduler;
import com.crypto.laplace.service.*;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.atomic.AtomicReference;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.ObjectProvider;

class LaplaceSessionManagerTest {
 LaplaceStrategyProperties properties=new LaplaceStrategyProperties();LaplacePaperExecutionService execution=mock(LaplacePaperExecutionService.class);LaplacePaperPositionRepository positions=mock(LaplacePaperPositionRepository.class);StartupMarketUniverseService universe=mock(StartupMarketUniverseService.class);LaplaceStartupHistoryService history=mock(LaplaceStartupHistoryService.class);LaplaceBreadthService breadth=mock(LaplaceBreadthService.class);ObjectProvider<LaplacePaperTradeCoordinator> coordinator=mock(ObjectProvider.class);ObjectProvider<LaplaceThirtyMinuteScheduler> scheduler=mock(ObjectProvider.class);AtomicReference<Instant> now=new AtomicReference<>(Instant.parse("2026-01-01T00:00:00Z"));LaplaceSessionManager manager;
 @BeforeEach void setup(){when(execution.accountEquity()).thenReturn(new BigDecimal("250"));when(execution.projectedOpenNetPnl()).thenReturn(BigDecimal.ZERO);when(positions.findByStrategyAndStatus(any(),any())).thenReturn(List.of());when(positions.findByStrategyAndTradingRunIdAndStatus(any(),any(),any())).thenReturn(List.of());when(positions.findByStrategyAndTradingRunIdAndSessionIdAndStatus(any(),any(),any(),any())).thenReturn(List.of());when(universe.minimumVolumeThreshold()).thenReturn(new BigDecimal("20000000"));manager=new LaplaceSessionManager(properties,execution,positions,universe,history,breadth,coordinator,scheduler,now::get);manager.run(null);}
 @Test void startsAtConfiguredCapitalAndFixedMargin(){assertThat(manager.snapshot().capital()).isEqualByComparingTo("250");assertThat(manager.snapshot().margin()).isEqualByComparingTo("5");}
 @Test void marginScalesFivePercentWithEquity(){when(execution.accountEquity()).thenReturn(new BigDecimal("262.50"));manager=new LaplaceSessionManager(properties,execution,positions,universe,history,breadth,coordinator,scheduler,now::get);manager.run(null);assertThat(manager.snapshot().margin()).isEqualByComparingTo("5.250000000000");}
 @Test void marginCompoundsFromBaseReferences(){when(execution.accountEquity()).thenReturn(new BigDecimal("267.75"));manager=new LaplaceSessionManager(properties,execution,positions,universe,history,breadth,coordinator,scheduler,now::get);manager.run(null);assertThat(manager.snapshot().margin()).isEqualByComparingTo("5.355000000000");}
 @Test void hardResetKeepsTradingRunButChangesSession(){String run=manager.tradingRunId(),oldSession=manager.currentSessionId();when(universe.isReady()).thenReturn(true);when(history.readySymbols()).thenReturn(Set.of("BTCUSDT"));now.set(now.get().plusSeconds(12*3600));manager.tick();assertThat(manager.tradingRunId()).isEqualTo(run);assertThat(manager.currentSessionId()).isNotEqualTo(oldSession);}
 @Test void locksOnlyWhenBothProfitThresholdsPass(){LaplacePaperPositionEntity closed=closed("12.75");when(positions.findByStrategyAndTradingRunIdAndSessionIdAndStatus(eq(LaplacePaperExecutionService.STRATEGY),any(),any(),eq(LaplacePositionStatus.CLOSED))).thenReturn(List.of(closed));when(execution.projectedOpenNetPnl()).thenReturn(new BigDecimal("-1.00"));manager.tick();verify(execution).closeAllOpen(LaplaceSessionManager.PROFIT_LOCK_REASON);assertThat(manager.snapshot().lifecycle()).isEqualTo(LaplaceSessionManager.Lifecycle.LOCKED);}
 @Test void doesNotLockWhenProjectedReturnIsOnlyFourPointFive(){LaplacePaperPositionEntity closed=closed("12.75");when(positions.findByStrategyAndTradingRunIdAndSessionIdAndStatus(eq(LaplacePaperExecutionService.STRATEGY),any(),any(),eq(LaplacePositionStatus.CLOSED))).thenReturn(List.of(closed));when(execution.projectedOpenNetPnl()).thenReturn(new BigDecimal("-1.50"));manager.tick();verify(execution,never()).closeAllOpen(any());assertThat(manager.snapshot().lifecycle()).isEqualTo(LaplaceSessionManager.Lifecycle.ACTIVE);}
 @Test void blocksEntriesAfterTenHours(){String id=manager.currentSessionId();now.set(now.get().plusSeconds(10*3600));manager.tick();assertThat(manager.allowEntry(id,"BTCUSDT",PositionSide.SHORT,now.get(),Map.of("BTCUSDT",new BigDecimal("30000000")),true,1)).isFalse();}
 @Test void rejectsSignalFromPreviousGeneration(){assertThat(manager.allowEntry("old-session","BTCUSDT",PositionSide.SHORT,now.get(),Map.of("BTCUSDT",new BigDecimal("30000000")),true,1)).isFalse();}
 @Test void twelveHourBoundaryClosesReloadsAndStartsNewGeneration(){String old=manager.currentSessionId();when(universe.isReady()).thenReturn(true);when(history.readySymbols()).thenReturn(Set.of("BTCUSDT"));now.set(now.get().plusSeconds(12*3600));manager.tick();InOrder order=inOrder(execution,universe,history);order.verify(execution).closeAllOpen(LaplaceSessionManager.HARD_CLOSE_REASON);order.verify(universe).reload();order.verify(history).reloadFresh();assertThat(manager.currentSessionId()).isNotEqualTo(old);assertThat(manager.snapshot().lifecycle()).isEqualTo(LaplaceSessionManager.Lifecycle.ACTIVE);}
 @Test void reloadFailureLeavesRiskOffAndEntryDisabled(){now.set(now.get().plusSeconds(12*3600));doThrow(new IllegalStateException("reload failed")).when(universe).reload();manager.tick();assertThat(manager.snapshot().lifecycle()).isEqualTo(LaplaceSessionManager.Lifecycle.RISK_OFF);assertThat(manager.snapshot().entryEnabled()).isFalse();}
 @Test void hardResetWaitsUntilWholeScanReleasesReadLock() throws Exception {var entered=new java.util.concurrent.CountDownLatch(1);var release=new java.util.concurrent.CountDownLatch(1);Thread scan=Thread.ofPlatform().start(()->manager.processScan(context->{entered.countDown();try{release.await();}catch(InterruptedException e){Thread.currentThread().interrupt();}}));entered.await();when(universe.isReady()).thenReturn(true);when(history.readySymbols()).thenReturn(Set.of("BTCUSDT"));now.set(now.get().plusSeconds(12*3600));Thread reset=Thread.ofPlatform().start(manager::tick);Thread.sleep(50);verify(execution,never()).closeAllOpen(LaplaceSessionManager.HARD_CLOSE_REASON);release.countDown();scan.join();reset.join();verify(execution).closeAllOpen(LaplaceSessionManager.HARD_CLOSE_REASON);}
 private LaplacePaperPositionEntity closed(String pnl){return LaplacePaperPositionEntity.builder().exitTime(now.get().plusSeconds(1)).netPnl(new BigDecimal(pnl)).status(LaplacePositionStatus.CLOSED).build();}
}
